### ISSUE TITLE
Aragon Nest Proposal: Convergent - Unlock your personal economy

### ISSUE THREAD

**Issue by lsaether** [aragon/nest#110]
# Aragon Nest Proposal: Convergent - Unlock your personal economy

## Abstract

[Convergent](https://github.com/convergentcx) enables users to launch their own crypto token as a first step towards creating one's personal DAO. Customizable [bonding curves]((https://medium.com/@simondlr/tokens-2-0-curved-token-bonding-in-curation-markets-1764a2e0bee5)) ensure that this personal currency represents the market value of one’s future time, work or attention and that it is instantly liquid despite low volumes.

Many opportunities for human exchange never realize because the transaction costs of creating a market for them are too high. Blockchain tokens now allow us to formally represent values that are exchanged between individuals in informal and even future expected interactions. 

Convergent allows you to create your own personal cryptocurrency and back it by promising a service in exchange for payment in that token at a fixed rate. If you can credibly commit to honoring this commitment, the market will find a price for any service you may choose to offer. Market participants are incentivized to discover and invest in undervalued persons early on, helping the subject of the personal economy to raise funds today based on expected value streams in the future. In certain use cases individuals may automate the transaction of a service, giving more credibility and value to the token and moving one step further towards a world of personal DAOs. If designed correctly, the token could also give stakeholders voting rights over  decisions that the individual has chosen to be governed by her personal DAO.

Convergent is developing the two building blocks that are necessary for the emergence of personal economies: 

### [Arc](https://github.com/convergentcx/Arc)

Bonding curves offer the most transparent, fair and sustainable token pricing/distribution mechanism for personal economies. They guarantee instant liquidity despite the low trading volumes that most personal currencies will experience. However, there is a vast design space and numerous ways for an owner to extract value from a bonding curve. Different bonding curves will make sense for different personal economies. Therefore we are creating Arc, a framework with the standard set of smart contracts for dynamic, composable and upgradeable bonding curves, that allows users to customize the optimal bonding curve for their personal economy.

### [Arena](https://github.com/convergentcx/Arena)

Convergent is also creating the first platform through which users can access the Arc contracts in an intuitive way. Here they will be able to customize and launch their token, discover existing personal economies and purchase or invest in the offered services. Certain types of services will emerge as particularly suitable for tokenization. To help users transact these services and verify their delivery, the Arena platform will be complemented with marketplace extensions designed specifically for those use cases.

## Deliverables

 - Arena MVP live on testnet.
 - Arc composable bonding curve framework beta.
 - 10 vibrant personal economies launched on Arena.
 - 2 initial marketplace utility extensions.
 - Audit and optimization for smart contracts release.
 - Arena deployed to mainnet using Arc.

## Grant size

Funding: $100k in ETH, split into chunks paid out over achieved deliverables.

Success reward: Up to $50k in ANT, awarded at the completion of all deliverables.

## Application requirements

- [Organization repository](https://github.com/convergentcx) containing Arena and Arc.
- Convergent Team: [Logan Saether](https://logansaether.com) (@lsaether) and [Achill Rudolph](https://twitter.com/AchillRudolph) (@acrdlph) both committing full time
- ~$15000 /month
- Organizational structure: Team with intent to become a decentralized organization surrounding the development of open source code and inclusive community. We consider holocracy, an Aragon DAO or at some point in the future an [ADO](https://hackmd.io/3Un8Qi4_RBeOINmt9tFIDQ) using TCRs.

## Development timeline

The development timeline will be the following one in regards to each deliverable:

| Expected Timeframe | Feature Description |
| ------------------ | ------------------- |
| Month 1 | Arena MVP live on testnet |
| Month 2 | Arc bonding curve framework beta |
| Month 3 | Initial user base and active developer community |
| Month 4 | First marketplace extensions |
| Month 5 | Security and Optimization |
| Month 6 | Mainnet deployment |

Testnet launch will be expected during (January) Q1 2019 and mainnet deployment will take place (June) Q3 2019.

**Comment by mariapao** [comment]
Hi @lsaether thank you for submitting your proposal.

This is an interesting use case for bonding curves, however, we don't think this idea is a priority for Aragon nor for Ethereum right now. Thus, we have decided not to approve this proposal at the moment. In the future, if you are working on something that is a fit for the program, please apply again. We appreciate your participation very much.
