### ISSUE TITLE
Aragon Nest Proposal: Gitmining

### ISSUE THREAD

**Issue by coderwithattitude** [aragon/nest#112]
# Aragon Nest Proposal: Gitmining

## Abstract

It has been proven beyond reasonable doubt that Open source technology has had the most impact on technology advancement as a whole and software technology in particular, 

it removed steep barrier to entry that would have otherwise been a stumbling block to the existence of the many frontline companies we have today. 

We have all collectively taken more from Open Source System (OSS) than we put in and for that we are forever in its debt. 

For so long, mainly passion has oiled the wheels of open source development, while this is commendable and admirable, 

it is evident that the OSS community is long overdue for a model that adequately compensates contributors all over the world who day and night toil to create and maintain OSS without really expecting anything in return. This is what Gitmining hopes to achieve.

Gitmining is a blockchain application seeking to empower open source contributors and make it easier and more transparent for backers to fund OSS. 

Gitmining generates a graph that quantifies effort and will reward contributors commensurate to their efforts. 
We will be using parts of the [sourcecred](https://sourcecred.io/) platform and we hope to build gitmining to complement the existing efforts to drive more funding to opensource projects.

Gitmining is on a mission to:

- Create a viable financing opportunity for OSS contributors
- Create a new avenue for community members to show support and back their OSS of interest
- Decentralize the OSS backing process and mitigate corporate control

## Deliverables

1. UI/UX design mockups for the gitmining platform
2. A set of AragonOS-compatible smart contracts to fund and reward OSS contributors with ERC20 tokens and ETH
3. A web interface to let users fund OSS projects, garner funding for their project and find OSS projects to contribute to and get paid
4. port instance of Gitmining to work within Aragon core

## Application requirements

- Team: [Babayemi Olulana](https://github.com/coderwithattitude), [Omoyeni Omotola](https://www.linkedin.com/in/omoyeni-o-240931ab/) ,[Adebayo Adegbemi](https://github.com/adibas03), [Daniel Onuchukwu](https://www.linkedin.com/in/danielonuchukwu/), [Kolade Abiodun](https://www.linkedin.com/in/abiokay/)
- monthly burn rate will be $20,000 per month.
- Gitmining is completely open source

## Grant size

Funding: $100k in ETH, split into chunks paid out over achieved deliverables.

Success reward: $50k in ANT, given out when all deliverables are ready.

## Development timeline

The development timeline will be the following one in regards to each deliverable:

- Month 1: UI/UX design for gitmining platform
- Month 1 - 2: Smart Contract System design 
- Month 2 - 4: Dapp interface design implementation 
- Month 5: Gitmining instance implemantion for Aragon Core.

Testnet launch will be expected Q3 2019, with mainnet launch being Q4 2019

**Comment by mariapao** [comment]
Hi @coderwithattitude Thank you for submitting your proposal. 

Open source sustainability is key. This is why we have funded teams that are working on it ([Pando](https://github.com/aragon/nest/pull/31), [TPS](https://github.com/aragon/nest/pull/24), [Wetonomy](https://github.com/aragon/nest/pull/70)). Sourcecred is certainly an interesting approach to the problem, however, right now we are prioritizing other key tools and applications for Aragon. Thus, we are not moving forward with this proposal this time. Thank you for your participation!
