### ISSUE TITLE
DecentraCorp

### ISSUE THREAD

**Issue by stan36** [aragon/nest#113]
# Aragon Nest Proposal: DecentraCorp

## Abstract

DecentraCorp is the world's first Decentralized Autonomous Corporation
where the CEO’s and shareholders are the same people who build and maintain
the machinery.

DecentraCorp’s goal is to empower the individual
with the tools and technology to build a better world!

To reach this goal DecentraCorp will employ the use of
Distributed Ledger Technologies starting with IPFS and
smart-contracts on the Ethereum Virtual Machine
(both on and off the Ethereum Mainnet).

Utilizing these technologies
DecentraCorp aims to provide the open source and
makers communities with a framework to help tinkerers and builders
earn a living for doing what they love while simultaneously helping to better their communities!

DecentraCorp relies heavily on its first project, The CryptoPatent Blockchain (In Alpha) to make all this possible. The CryptoPatent Blockchain is an open-source patent system which allows replications of any idea to mine IdeaCoin when they are used. The CryptoPatent Blockchain will exist on a second-layer Proof of Authority network anchored to the Main Ethereum Network.

A early Working Alpha of the project can be found at DecentraCorp.now.sh

-Documentation for DecentraCorp and its associated projects can be found at:
  -DecentraCorp: https://drive.google.com/open?id=1hhsuQ_JnBz5E0813V-4trPZhiflaTBwr

  -CryptoPatent Blockchain:
  https://drive.google.com/open?id=1Me8pn45kzBCucV-F1LyjYHv4LLBKWX6w

  -ChaosCasino:
  https://drive.google.com/open?id=12Fw9pM8V9B1zs1QvsQpNDL504ylq84Ic

  -GitHub:
   https://github.com/stan36/DecentraCorp

## Deliverables

1.Further Development of the EPMS (Embedded Program Mining Software) Alpha Version
2.Further Development Of the Ethereum MainChain Based DecentraCorp Contracts using Aragon
3.Development of the Node.js based CrossChain Smart-Contract Relay
4.DecentraCorp Beta Project Deployment
5.Bug Bounty/Community Engagement Campaign
6.Project Launch!

## Grant size

Funding: Up to $100k in ETH, split into chunks paid out over achieved deliverables.

Success reward: Up to $50k in ANT, given out when all deliverables are ready.

## Application requirements

-$5000 upon application approval for the Acquisition of necessary equipment including new computers for the team and multiple raspberry pi's along with assorted parts.
-$5000 to retain legal counsel for the entire project
-$15000 a month to cover the payroll expenses of five people for 6 months until the project is in its Beta release, at which point it should be capable of sustaining itself financially Via the on-chain contracts membership sales.
-Organizational Structure: upon receipt of the Grant a team of up to three developers will be hired on to further development of the project and carry it to completion. Positions being filled would include two react developers and a Python developer. Upon completion of the Projects Beta Phase, project development will transition to fully open source! DecentraCorp operates as a meritocracy where an individual is judged by what they have contributed to the community!

## Development timeline

1.February 2019
2.March 2019
3.May 2019
4.June 2019
5.July-October 2019
6.October 2019

**Comment by stan36** [comment]
Hello @mariapao, thank you for reviewing my proposal. I understand that from my proposal it appears my project is only built using Aragon, in fact when I applied for the grant this was my level of understanding. Since I submitted my application I have been combing through the Aragon documentation and as I do I have realized that there are several Aragon apps that I would need to develop in the process, including a "Buy Membership" application I began working on yesterday. I am also interested in providing Aragon with a way of offering a DAO thatsembership is not based off of token ownership. If I where to retool my proposal to be centered around the development of these applications, would it be appropriate to reapply?  As a follow up question, was the fact that I do not yet have a development team a major part of your decision? I have tried to include others on the project but without funding the only people I have been able to find have been unreliable.

**Comment by mariapao** [comment]
Hi @stan36 if what you are working on is considered a key app for Aragon and it is within the priorities of the project you can always apply again. In the next couple of weeks, we will let people know what is it that we consider a priority or a key application for the project in 2019. 

Regarding your question about the team, you can be a one-person team as long as you have the skills necessary to build the apps/tools you are proposing to build
