### ISSUE TITLE
Aragon Nest Proposal: Visualizing Consensus, an Ethereum Protocol Developer Course

### ISSUE THREAD

**Issue by K-Ho** [aragon/nest#118]
# Visualizing Consensus Proposal: Ethereum Protocol Developer Course for Cryptoeconomics.study
## Abstract

[Cryptoeconomics.study](https://cryptoeconomics.study/) is on track to become the largest free, open-source course on Blockchain protocols and Cryptoeconomics. 

_Visualizing Consensus_ proposes to build upon the [coding project](https://github.com/K-Ho/code/tree/networkVisualization) of the Cryptoeconomics.study course by building **organized programming assignments** and **interactive testing sandboxes** that will teach developers everything from the fundamentals of Cryptoeconomics up to the inner workings of Ethereum 2.0.

### Situation: 
There are many talented developers who are interested in contributing to Ethereum protocol research and development, but fail to get past the complicated proofs, diagrams, and jargon in white papers, specs, blog posts, and the Ethresear.ch forums. The Cryptoeconomics.study [lectures](https://youtu.be/m-0escxJ-j8) by Karl Floersch and [book](https://github.com/cryptoeconomics-study/website/tree/master/book) by Jinglan Wang are on track to serve as great resources to help explain these protocols, but the coding project of the course, which will teach students how to actually implement the protocols, has not seen development (aside from our contributions) in the past 3 months.

### Proposal:
Our mission for the _Visualizing Consensus_ coding project is to take student developers to the stage where they can start making pull requests to the Ethereum 2.0 protocol. We aim to make open-source blockchain protocol development accessible to all developers by guiding them through iteratively building, testing, attacking, and then improving a peer-to-peer payment protocol in Javascript until they construct something very similar to Ethereum 2.0. _Visualizing Consensus_ consists of robust coding assignments implementing protocols and attacks, as well as interactive sandboxes where students can visualize their implementations in a realistic network simulation.

## Deliverables

For all of our deliverables, you can track our progress via our [project board](https://github.com/K-Ho/code/projects/1).

Our 3-month deliverables are as follows:
1.	(5 weeks) Website (accounts, progress tracking, in-browser coding and testing) + refactoring codebase
2.	(3 weeks) Central payment operator (Sections 1.0-1.5) sandbox + coding assignments
3.	(2 weeks) Naive Client-Side Validation (Sections 2.1-2.2) sandbox + coding assignments - We have a [live demo](https://k-ho.github.io/code/) of our Section 2.1-2.2 sandbox and a [walkthrough](https://youtu.be/LWKHs7Zfq34) of the demo with Karl in the lectures.
4.	(3 weeks) 99% Fault Tolerant Consensus (Section 2.3) sandbox + coding assignments

Our 6-month deliverables will be as follows: 
1.	(2.5 weeks) Proof of Authority (Section 2.4) network sandbox + coding assignments 
2.	(5 weeks) Proof of Work Blockchain (Section 3.0) sandbox + coding assignments
3.	(5 weeks) Casper Beacon Chain (Section 4.0) sandbox + coding assignments

Our 9-month deliverables are subject to change with ETH2.0 specs and Cryptoeconomics.study course material, but will tentatively be as follows: 
1.	(5 weeks) Sharding (Section 4.x) sandbox + coding assignments
2.	(6 weeks) Plasma (Section 5.0) sandbox + coding assignments
3.	(2 weeks) Finalize tests and instructions for coding assignments

## Grant size

Funding: Our total budget for the full 9-month project is $115k. We are seeking up to $100k in ETH, paid as three separate chunks, one upfront, the second after our 3-month deliverables (course website + sections 1.0-1.5, 2.0-2.3)  are released, and the third after our 6-month deliverables (sections 2.4, 3.0-3.x, 4.0) are released. 

Success reward: Up to $50k in ANT, given out when all deliverables are complete and the full Cryptoeconomics.study course is launched.

## Application requirements

- Full details of our current progress 
- Mockups of a full section of the course
- Details of the team members
- Full budget spreadsheet - (Estimated average burn rate for completing the deliverables)
- Deliverable details and specifications

## Development timeline

The development timeline will be the following one in regards to each deliverable:

1. March 2019
2. June 2019
3. Sep 2019

The full Cryptoeconomics.study course will be launched on **Sep. 1, 2019**, consisting of the _Visualizing Consensus_ coding assignments and interactive sandboxes, as well as the book and lectures.

**Comment by DaniellMesquita** [comment]
@K-Ho
This course could be on Education Platform: https://github.com/aragon/nest/issues/123
Or your team could contribute on it and include your course

**Comment by mariapao** [comment]
Hi @K-Ho thank you for submitting your proposal. 

We totally believe the mission of cryptoeconomics.study is very important. Unfortunately, the Nest program right now is focusing on funding teams working on Aragon infra and key Aragon apps. Therefore, we have decided not to approve this proposal.

I apologize for the slow responsiveness but right now the Nest program is through some changes such as its budget been approved by the token holders on Jan 24th.

**Comment by K-Ho** [comment]
Thanks @mariapao for the response. Totally understand your Aragon focus. 

We really need funding to finish getting this course out there to the public, and we'd really appreciate any small personal donations of 10-50 DAI on [Gitcoin Grants](https://gitcoin.co/grants/16/cryptoeconomicsstudy-free-open-source-blockchain-2) (from anyone who sees this!). They're matching donations through [Liberal Radicalism](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3243656), so small donations may be matched by upwards of 2,000%. Here's a [tutorial on how to donate](https://medium.com/gitcoin/fun-with-funding-contributing-to-a-gitcoin-grant-bfd17b31caa8) <3
