### ISSUE TITLE
Aragon Nest Proposal: GuildHub, a governance tool for gaming groups

### ISSUE THREAD

**Issue by martindale** [aragon/nest#121]
# Aragon Nest Proposal: GuildHub, a governance tool for gaming groups

## Abstract
Most governance tools are general-purpose.  By tailoring our experience to a single community, we can refine a product which is tailored to their unique requirements.  GuildHub will be a standalone application which integrates with [RPG](https://www.roleplaygateway.com), a community of over 150,000 game designers & players, to facilitate self-directed organization of clans, guilds, and factions in the virtual world, and [Aragon](https://aragon.org/), a decentralized governance platform.

## Deliverables

1. `0.1.0` desktop & web applications for GuildHub, including group creation & management
2. virtual asset issuance & management, driven by multi-sig from group
3. deployed to [RPG](https://www.roleplaygateway.com/about) and enabled for 40,000 beta users

## Grant size

Funding: $66,000 or equivalent
Success reward: $50,000 or equivalent

## Application requirements

- `0.1.0` release implementing:
  1. Group creation
  2. Group member management (add and remove)
  3. Group control management (various power levels)
  4. Group Chat
  5. Shared Asset Management
- Deployed User Interface to the Legacy Web (HTTP)
- Compiled Desktop Builds for Windows, MacOS, Ubuntu, and RedHat

All other requirements have been met; resource allocations provide for ~3 developers and designers over the 6 month deliverable timeline.  Success contingency goes on to fund `0.2.0` & community engagement for our 150,000 users (~2,000 DAU).

## Development timeline

1. March 1st, 2019: `0.1.0-alpha`, all basic functionality
2. May 3rd, 2019: `0.1.0-beta`, UI fully implemented
3. July 5th, 2019: `0.1.0-RC1`, release candidate and final bug squashing

**Comment by mariapao** [comment]
Hi @martindale thank you for submitting your proposal.

This is a very interesting use case for Aragon. However, right now we are focusing on funding teams working on Aragon infra and key apps. We are working on making it possible for people to be able to tailor their DAOs and tools to their specific use case. 

I apologize for the slow responsiveness but right now the Nest program is through some changes as its budget been approved by the token holders on Jan 24th.
