### ISSUE TITLE
Humanomics 

### ISSUE THREAD

**Issue by Humanomics** [aragon/nest#126]
_See the [Guide for submitting a proposal for grants](https://wiki.aragon.one/nest/guides/guide_for_submitting_a_proposal_for_grants/) for further details on submitting a grant proposal_

# Aragon Nest Proposal: Seed Grant
HELLO EAGLES 
## Abstract

The blockchain industry has been growing tremendously in the last 10 years. Yet, it is still very volatile and difficult for the majority of world population to access and take real advantage of these fancy things. Also, most popular blockchain platforms are based on either PoW or PoS or Hybrid consensus algorithms. These algorithms are vulnerable to different type of attacks that lead to centralization of wealth.

Humanomics is a blockchain ecosystem that is set to decentralize wealth generation. Where people, services, small to large businesses, innovations, applications, commodities, individuals and much more from anywhere in the world can participate in a profoundly interconnected  social economic growth, where anyone's participation is in everyone else's interests. We are aiming to bring real life solutions through dynamic technology experiences. 

[ONEPAGER.pdf](https://github.com/aragon/nest/files/2770598/ONEPAGER.pdf)

## Deliverables

1. Frontend development
2. Backend development
3. Blockchain development
4. UI/Operator dashboard (Admin/user)
5. Value-smart/Smart contract tests
6. Q/A

## Grant size

So far we have been contributing our time and own resources to get to this stage. We already beyond the R/D phase with our products, and to continue with fundamental implementations funding is necessary.

Funding: Up to $200k in ETH, split into chunks paid out over achieved deliverables.

Success reward: Up to $50k in ANT, given out when all deliverables are ready.

## Application requirements

Here is our demo website containing the following: 
- Technical White Paper 
- Full page with details about the concept
- Short video
- Road map

www.x9c.xyz
www.nexgensm.com - Outsource team

## Development timeline

The estimated time of completion is up to 27 weeks.

1. UI/Operator dashboard.   (1-2 weeks)
2. Business requirement / test plans.   (2-4 weeks)
2. Q/A.   (8-16 weeks)
3. Frontend development / Backend development / Blockchain development.   (20-26 weeks)

#### Nasser Sultan 
Project Lead - Futurist 

#### Naveen Ravindran
Blockchain Architect 

#### Rahul AR
Sr. Blockchain Architect - Lead Developer

#### Shyama L Kenth
Business & Q/A analyst 

#### Manuyash
Artificial Intelligence - CL/CV researcher

#### Rajesh
UI/UX Designer

**Comment by mariapao** [comment]
Hi @Humanomics thank you for submitting your proposal. 

The Nest program this year is focused on Aragon only. We will fund teams building Aragon infra, tools and/or applications. Thus, this proposal is not a fit for the program and it is not approved. 

If in the future you are working on something that is a fit for the program, please do not hesitate to apply again.
