### ISSUE TITLE
A Decentralized Dohnut Protocol: #128

### ISSUE THREAD

**Issue by burrrata** [aragon/nest#128]
# Dohnuts: decentralized donuts 🍩

## Abstract

There are a lot of people on web2 platforms who are constrained by the centralization of those platforms. There are not a lot of people on web3 platforms, but web3 allows people to break free of the constraints of web2 monopolies and platforms. As we can see from the recent controversy over /r/ethtrader donuts there is clearly demand for better systems of governance and social engagement. People want a safe place to augment their communities with on-chain voting, governance, and anything else they can imagine!  

I'd like to help make the dream of decentralized permissionless communities a reality by contributing a fully decentralized market based on-chain voting mechanism, a web2/web3 data bridges/oracle, and community incentivization/engagement models that people can explore. This will start with a decentralized version of the erc-20 donuts that briefly debuted on /r/ethtrader, but will be modular so people can change it as they wish invent their own usecases and models. Ideally this will create a protocol/template for anyone to extend their web2.0 community (starting with Reddit) to include web3.0 capabilities. While the usecase for each community/application will be specific, the core framework can be generalized to make it as easy and fast as possible for people to iteratively start exploring in that direction (web2 => web3).

Currently this would be very expensive on Ethereum... but Parity just released Substrate which integrates seamlessly into Polkadot, is on track to scale nicely, and has a great dev experience. Since it looks like Aragon is also exploring transitioning to Polkadot/Substrate I'd like help by contributing a framework/toolbox that makes it easy for communities to experiment transitioning from web2 to web3 via Aragon and Substrate! :) 
- Note: since Substrate is about as modular as it gets, if Ethereum proves to be the better choice at any point in time, the general framework for this protocol can be ported over.

### Background on Reddit donuts and the /r/ethtrader experiment

FAQ on tradeable erc-20 donuts from /r/ethtrader
- TL;DR: they're a link between Reddit karma and a tradable erc-20 token that allows you to buy voting power and use it for stuff like banner ads, polls, and dethroning mods on the subreddit.
- https://www.reddit.com/r/donuttrader/comments/aisb0k/donut_faq_megathread_general_discussion/

Brainstorm on what this protocol and tools might look with identity, oracles, and voting mechanisms.
- https://www.reddit.com/r/donuttrader/comments/ajje9p/make_donuts_decentralized_again/

A repo where I'm starting to aggregate useful ideas and will start to build the first prototype.
- https://github.com/burrrata/DOH

## Deliverables

Draft / Whitepaper of the system.
- explains the core components of the system and outlines what they need to do
  - web2 => web3 identity
  - web2 => web3 data transfer and verification
  - web3 mechanisms for voting and trading => action on web2 platforms/communities that use the mechanism (for example a subreddit that chooses to make their decisions from the web3 votes of the community)

An oracle/validator model that connects data from web2 platforms to web3 contracts/markets.
- A system that can be managed by the participants of the data network in a social/cryptoeconomic manner rather than a 3rd party service. This reduces 3rd party risk and allows a community to bootstrap the protocol rather than being constrained by what 3rd parties do or don't support.

A live demo: the decentralized dohnut protocol.
- Shows how the whole thing works and provides a template for people/communities to learn about and start testing bridging their web2 experiences to web3 opportunities (this will be like the /r/ethtrader donuts, but actually decentralized).
- The template will also come with a toolkit for quickly building and experimenting with cryptoeconomic voting, governance, and incentivization mechanisms (building blocks for social decentralized communities).

## Stretch Deliverables!

If this project is successful it can then be extended via by integrating with other Aragon nest projects as well as projects from the broader Polkadot and Ethereum communities :)
- bridges from Polkadot to Ethereum and other blockchains to give communities access to the erc-20 market and liquidity pools
- zero knowledge systems for anonymous voting/identity mechanisms
- community engagement and education materials

## Grant size

Funding: $90k, split into 3 chunks for the 3 deliverables

Success reward: Up to $50k in ANT, given out when all deliverables are ready.

## Development timeline

The development timeline will be the following one in regards to each deliverable:

1. March 2018
2. June 2018
3. Sept 2018

**Comment by mariapao** [comment]
Hi @burrrata thank you very much for submitting your proposal. 

This project is a very interesting governance experiment that we would love to see develop on Aragon. The idea has potential and running communities such as the communities on Reddit in a more open way is one of the key use cases for Aragon. However, we think there is still a lot of work to do on fundamental things like identity and reputation, oracles and voting mechanisms. All this work is currently underway by Aragon teams or by teams from the Ethereum community.  Also, it looks like you guys are at a very early stage of the project and you still need to validate some key assumptions. Deliverables such as a whitepaper or a demo are things that we would like to see in an application rather than having them as the finished product itself. 

For all the above, we have decided not to approve this proposal for the moment. If you continue working on the project make sure to keep us updated :)
