### ISSUE TITLE
Aragon Nest Proposal: ScalingNOW! Interview Series and Conference on Scaling Solutions for DApps

### ISSUE THREAD

**Issue by alexandraheller** [aragon/nest#13]
## Abstract

Ethereum is dealing with major scaling issues, and Giveth has settled on a stop-gap solution for our own DApp as [outlined here](https://medium.com/giveth/tackling-ethereum-scalability-issues-29bd700b5060).

However, this is a temporary fix—we are dedicated to decentralization, and this is a very centralized approach.  

The long-term solution to the scaling issue is Sharding, which is likely to come to the Ethereum blockchain in 2019 or 2020. However, we need #ScalingNOW! 

To find our scaling solution, we need to interview scaling experts. ScalingNOW! is a project to quickly consolidate and distribute all the information we find on scaling solutions with other DApp teams so that they can cut research time and focus on development. 

ScalingNOW! will accomplish this by completing the following:
* Livestreaming 10+ interviews with leading scalability experts
* Hosting a donation-based ScalingNow! conference with leading scalability experts on March 6, 2018
* Consolidating the information gathered into easily digestible Medium posts
* Actively distributing the Medium posts to the larger DApp development community by sharing to the relevant Reddit and Telegram communities

By funding ScalingNOW!, Aragon Nest will help DApp teams quickly find the best scaling solution for their project and thus propel the entire DApp ecosystem forward. :rocket:

## Deliverables
* Interviews with the following scaling experts, in video and Medium post format:
  * [Björn and Max from Parity](https://www.youtube.com/watch?v=aWvzQMorof0)
  * [Igor and Roman from POA Network](https://youtu.be/WTlYwqT7bA0)
  * Alex from GridPlus
  * Sina from Truebit
  * Liam from Counterfactual
  * A representative from Raiden
  * Several other scaling experts
* ScalingNOW! conference on March 6th in Barcelona. 

## Grant size
Funding: 10+ interviews at 0.5 ETH/interview. Conference costs to be determined. 

## Application requirements
* Team members:

Griff Green — Researcher & Developer
Founder @ Giveth
 [GitHub](https://github.com/GriffGreen) [Twitter](https://twitter.com/thegrifft)

Lindsay Goldstein — Project Manager
Project Manager @ Giveth
[LinkedIn](https://www.linkedin.com/in/lindsay-goldstein-29b9761b/) 

Kay Gertler — Conference Website Creator + Multisig Deployer
Developer @ Giveth
[LinkedIn](https://www.linkedin.com/in/kay-gertler/) [Twitter](https://twitter.com/krassvs)

Alexandra Heller — Communications
[LinkedIn](https://www.linkedin.com/in/alexandraheller/) [Twitter](https://twitter.com/a13xndra)

* Estimated average burn rate for completing the deliverables: .05 ETH/interview

* Legal structure: Giveth DAC

## Development timeline
Interviews will be posted in February and March, the conference will be hosted on March 6th.

**Comment by mariapao** [comment]
@alexandraheller Thanks a lot for submitting your proposal. Scaling is certainly a problem we would love to help solving. However, we don’t think the scalingNOW project is a fit for the program. We are focused in funding the development of fundamental basic tooling for Aragon and Ethereum. We are not funding conferences nor interviews at the moment. Thus, your proposal is not a candidate for funding this time. We appreciate your participation very much. If in the future you are working on something that is a fit for the program, do not hesitate to apply again!

I'm closing the issue.

**Comment by alexandraheller** [comment]
@mariapao We understand, that makes sense. Thanks so much for your consideration!

**Comment by GriffGreen** [comment]
Thx Maria!!!
