### ISSUE TITLE
Aragon Nest Proposal: Cartesi

### ISSUE THREAD

**Issue by erickmoura** [aragon/nest#130]
# Aragon Nest Proposal: Cartesi

## Abstract

Cartesi is a layer-2 infrastructure that allows applications to reach consensus over off-chain computations that happen inside a realistic (RISC-V) architecture running Linux.

This technology will allow developers to build the complex logic of their dApps in Linux, using their favorite languages, libraries and OS resources (file-systems, processes, sockets, etc.). And all this happens at the second layer, with negligible fees on the main chain, but with strong dispute resolution guarantees.

We have developed an isolated RISC-V architecture that is emulated in a deterministic and reproducible way (bit-by-bit). Then we can use an interactive verification (sometimes called "verification game") to settle disputes that may arise over the results of such computations (with negligible costs on the blockchain). This interactive procedure is similar to Truebit, although Cartesi differs substantially in architecture and in the way economic incentives are organized.

We reached an MVP in December/2018. The MVP includes Cartesi's RISC-V emulator that different involved parties run and agree on the results of computations that were specified by the smart contract (see link below). We're currently approaching the conclusion of most of the implementation of the Cartesi Core, as specified in the tech paper (link below).

## Vote Tallying with Cartesi

Cartesi will offer a robust alternative to optimist incentivized relays as described on [this post](https://blog.aragon.one/optimistic-meets-off-chain-data-availability/).

We will implement a tallying vote system that provides a "unanimous consensus" where input data availability is ensured. This is a summary of the proposed protocol. 

1. Suppose a set of potential validators, where each validator is represented by a Cartesi Node
2. A user requests a computation (fees can be negotiable)
3. Each potential validator that wants to participate first acknowledges the availability and integrity of the input data and places a security deposit. The placement of the deposit gives it the right to propose or challenge a result
4. A proposer is appointed randomly or using any preferred method.
5. Once the first validator runs the computation and proposes a result to the blockchain, a challenging period begins
6. During this period, any other validator that placed a deposit can challenge a dishonest result
7. In case there is a challenge, a "verification game" is established between the challenging and the proposing node
7. The "verification game" identifies the dishonest validator at negligible cost to the blockchain
8. Other validators also have the chance to challenge previously asserted results
9. As long as there is one honest validator, the correct result of the computation is guaranteed 

Advantages compared to the incentivized relays:

- No requirement for reaching a quorum of 2/3 of validators agreeing on a result. One proposer node will suffice, as Cartesi will provide "unanimous consensus". Safety can be guaranteed as long as there is one honest validator.

- Users are free to download a Cartesi Node to run a validator node to represent him/herself.

# References

[Cartesi website](https://cartesi.io/)
[Cartesi tech paper](https://cartesi.io/cartesi_whitepaper.pdf)
[Dose of Ether podcast episode](https://thebitcoinpodcast.com/dose-of-ether-6/)
[MVP Video](https://www.youtube.com/watch?v=BuepnE0HMf4)
[Medium](https://medium.com/cartesi)

## Deliverables

The following table shows the roadmap with the deliverables.

Expected Time | Deliverables
|:-----------:|:---------:|
1 month | Cartesi Core without DAG
3 months | DAG + SDK 
2 months | Vote Tallying for Aragon

## Grant size

Funding: Up to $100k in ETH, split into chunks paid out over achieved deliverables.
Success reward: Up to $50k in ANT, given out when all deliverables are ready.

## Development process

Cartesi started the development in July/2017. 
It has been progressing steadily and getting more speed in the last months.
We practice scrum, with 2-week sprints. 
We have been publishing our development progress through frequent Medium articles (link above).

**Comment by mariapao** [comment]
Hi @erickmoura thank you for submitting your proposal. We have been reviewing the proposal and getting to know the project a bit. 

We think Cartesy is a very interesting and ambitious project that has the potential to bring an important improvement in terms of scalability. As you said, it can be an alternative to optimist incentivized relays. Unfortunately, we are focusing our resources on the optimist incentivized relays solution for the moment. Also, the program right now is looking for teams working on tools and key applications specifically for Aragon. We are not interested in founding platforms nor businesses. Therefore, we have decided not to approve this proposal. 

If in the future you are working on something that is a fit for the program, please do not hesitate to apply again.

**Comment by erickmoura** [comment]
Thanks for reviewing our project and feedback, @mariapao.
