### ISSUE TITLE
Aragon Nest Proposal: implementing Gossipsub

### ISSUE THREAD

**Issue by jamesray1** [aragon/nest#132]
# Aragon Nest Proposal: Gossipsub

## Abstract

Currently Ethereum, [Substrate](https://github.com/paritytech/substrate/), and [Polkadot](https://polkadot.network/) use [floodsub](https://github.com/libp2p/specs/tree/master/pubsub), a PubSub protocol that floods to all peers. This wide amplication is not efficient, nor scalable, which conflicts with the scalability goals of Ethereum 2.0. [Gossipsub](https://github.com/libp2p/specs/tree/master/pubsub/gossipsub) is a PubSub protocol that involves publishing and subscribing to some limited set of peers, using randomized topic meshes and gossip. This grant proposal is seeking to fund the development of gossipsub and integration into Ethereum 2.0 clients, such as [paritytech/shasper](https://github.com/paritytech/shasper), and Polkadot.
 
## Deliverables

1. Implementing [gossipsub](https://github.com/libp2p/specs/tree/master/pubsub/gossipsub). If a libp2p implementation is not implemented in the chosen programming language, then that would need to be developed first. In such a case, Protocol Labs may be sought ought for funding, although funding may also be considered for this.
2. Write tests.
3. Integrate into a p2p network or blockchain such as IPFS, Ethereum 2.0 and Polkadot.

## Grant size

Funding: Up to $100k in ETH, split into chunks paid out over achieved deliverables.

Success reward: Up to $50k in ANT, given out when all deliverables are ready.

## Application requirements

- Details of the team members, including relevant experience
- Estimated average burn rate for completing the deliverables
- Legal structure to be adopted, if any
- License structure (open source code with a free license such as CC0, MIT, or GNU GPL v3 is required)

## Development timeline

The development timeline will be the following one in regards to each deliverable (some flexibility around this timeline may be allowed in accordance with the team and possibly other commitments that they may have):

1. Around 4–6 months to implement gossipsub. This doesn't include implementing libp2p.
2. Another month or so to write tests.
3. Around 3–6 months to implement and demonstate in a testnet then a live p2p network.

**Comment by mariapao** [comment]
Hi @jamesray1 thank you for submitting your proposal. 

First, apologies for the slow reply. We have been working on the priorities for Nest this year.

What you are trying to achieve with Gossipsub is certainly important. Unfortunately, this project is not aligned with the priorities of the program at the moment. We are focusing on teams working on tools, infra and key applications for Aragon that will help to have a product more satisfying to the users. 

If in the future you are working on something that fits the above-mentioned priorities, please do not hesitate to apply again.
