### ISSUE TITLE
Aragon Nest Proposal: Instant GUI widgets for any smart contract

### ISSUE THREAD

**Issue by patrykadas** [aragon/nest#133]
## Abstract
With almost two million deployed smart contracts and only around five hundreds daily dapp users, we want to improve the ease and accessibility of interactions with smart contracts.

Dappi is a tool to instantly create an embeddable, self-contained widget for any smart contract in three steps: pre-define functions, customize the look, use. It does not require any coding experience nor familiarity with the Web 3.0 stack and it provides accessibility and ease of use for the end user.

More details:
[Product marketing page](http://ontop.team/dappi)
[Example of a video ad](https://youtu.be/5IqUdBAgVGw)
[Where it started](https://twitter.com/patrykadas/status/1092468765252612096)
[Design file](https://www.figma.com/file/P6G4CuHmVGKZVdR9JQ5GStx9/Dappi-product?node-id=0%3A1)

## Deliverables
* A deployed application that allows creating an embeddable, self-contained working interface in a form of a widget.
* Series of short videos and blog posts highlighting particular use cases for different groups.
* A dedicated page with “Powered by Dappi” examples

## Team
Most of our team worked together for more than a year. We’ve won EthBuenosAires and launched two dapps, one of which was an embeddable web 3.0 widget.

1. **Patryk Adaś** - a product designer, prototyped various solutions for a speculative browser for Mozilla, designed product flows and UI for API marketplace Mashape.com and gained experience in building for Web 3.0 an information discovery platform based on economic signals at Tokntalk.club / Userfeeds.io.
[patrykadas.com](http://patrykadas.com)

2. **Grzegorz Kapkowski** - a software developer with over 10 years of experience. He has built Userfeeds and launched several blockchain products like Userfeeds Platform, LinkExchange or Tok’n’talk. He holds patents in metadata aggregation algorithms.
[https://github.com/gkapkowski](https://github.com/gkapkowski)

3. **Jakub Stasiak** - a full stack engineer, worked on Userfeeds / Tok’n’talk. Experienced in Web3js and IPFS, previously Nokia.
[https://github.com/jakubsta](https://github.com/gkapkowski)

4. **Piotr Wojtczak** - a motion designer and art director, created stories for both small blockchain startups (Tok’n’talk, Ramp) and established brands (H&M, Sony).
[https://piotr.works/](https://piotr.works/)

5. **Mateusz Sikora** - a software engineer, currently building frontend at Gravete Corp, a former Nokia employee.
[https://github.com/mateuszsikora](https://github.com/mateuszsikora)

## Grant size
Funding: $60k in ETH, split into $20,000 chunks paid out over 3 Milestones.
Success reward: $20k in ANT, given out when all deliverables are ready.

## Development timeline

The development timeline will be the following one in regards to each deliverable:

Timeframe | Goal
------------ | -------------
1 month | Working version. Link generation, library, embeddable widget. Storyboards and use cases.
2 month | Stable version. UX improvements (address verification, more efficient states communication, etc.), predefining functions. First blog posts and videos.
3-4 month | Polished version. Increased accessibility, covering edge cases.

**Comment by mariapao** [comment]
@patrykadas Thank you for submitting your proposal!

We have been reviewing your proposal and the work that you guys are doing, which is very interesting. You are doing some cool UI experiments! Unfortunately, this current project is not aligned with the priorities of the program at the moment. Nest is focusing on teams working on tools, infra and key applications for Aragon (mainly) that will help to have a product more satisfying to the users. Therefore, we have decided not to approve this proposal.

If in the future you are working on something that fits the above-mentioned priorities, please do not hesitate to apply again and let's keep in contact!
