### ISSUE TITLE
Aragon Oracle Manager

### ISSUE THREAD

**Issue by cwhinfrey** [aragon/nest#138]
# Aragon Nest Proposal: Oracle Manager

## Abstract

Decentralized price oracles are increasingly paramount to blockchain based financial organizations and mechanisms including the upcoming [Aragon Futarchy App](https://github.com/levelkdev/futarchy-app). Decentralized applications that require a price oracle have, for the most part, opted to use centralized oracle solutions while research on decentralized price feed oracles is ongoing. An Aragon Oracle Manager App would allow for easy creation and experimentation with decentralized price feed oracle governance.

__Aragon Oracle Manager App__

The Aragon Oracle Manager App will allow an Aragon DAO to manage a weighted registry of base oracles. A top level oracle contract will then take the weighted median value of the base oracles to provide a decentralized price feed. This price feed may be the value of the DAO's token or a more general price feed such as ETH/USD.

__Supported Governance Actions__

DAO participants will be allowed to kick off the following governance actions:

1. __Add base oracle__ - Adds a base oracle with a given weight
2. __Remove base oracle__ - Remove a base oracle from the registry
3. __Set base oracle weight__ - Changes a base oracle's weight in the registry

## Prior Code

- The Aragon Oracle Manager App will leverage the [Tidbit EVM Package](https://github.com/levelkdev/tidbit) for building oracles on Ethereum.

- Aragon price oracle support will be added to the [Aragon Futarchy App](https://github.com/levelkdev/futarchy-app).

## Deliverables and Timeline

Aragon Oracle Manager App deployed on testnet, with a user interface for managing base oracles. Support added to the Aragon Futarchy App to use price-feed data to resolve Futarchy decisions.

Estimated total timeframe of 3 months for project completion of these features:

| Expected Timeframe | Feature Description |
|--------------------|---------------------|
| Month 1            | UI mocks for Oracle Manager App |
| Month 1            | Finalize Tidbit data-feed oracles (`DataFeedOracleBase` and `MedianDataFeedOracle`) with unit tests |
| Month 1 - 2        | Build web UI |
| Month 2            | Finalize `OracleManagerApp` contract with unit tests |
| Month 3            | Integrate web UI w/ smart contracts, testnet deployment |
| Month 3            | Aragon Futarchy app integration |

## Grant size

Funding: $100k in ETH, split into chunks paid out over achieved deliverables.

Success reward: $50k in ANT, given out when all deliverables are ready.

**Comment by LouisGrx** [comment]
Hey There, given your [new proposal](https://github.com/aragon/nest/issues/158) I'm closing this one.
