### ISSUE TITLE
Aragon Nest Proposal: Kipos - A Research on Aragon as a Cooperative Housing Toolbox

### ISSUE THREAD

**Issue by bitsybloques** [aragon/nest#155]
# Aragon Nest Proposal: Kipos: A Research on Aragon As a Cooperative Housing Tool Box.
### Problem

Housing has become a major problem in cities like Barcelona. Speculation, banks monopoly of real estate, lobbies, gentrification and salaries stagnation are the main causes on this attack against one of the most important human rights. Furthermore, the colonization of sharing economy models doesn’t seem to be a solution but a way to perpetuate this endemic problem by a hyper-individualization of urban life.

The underlying financial structure that caused the last economic crisis has remained untouched and there’s is no rational expectation that local policies can reverse this situation. Locals seem condemned to a future of increasing precarity, almost a nomadic life without any ability to build meaningful collective networks and self-empowered communities.

New forms of collective acts of sovereignty are already emerging to face the housing crisis: cooperative building purchasing, communes, squating, popular resistance against eviction orders, rent strikes. Besides the perils and retaliation that this forms of resistance could face, a major handicap for the adoption of this forms of resistance is the lack of an optimal technological infrastructure to dynamically manage organizational disputes, funds, tasks and goals. Ethereum could provide a solution but due its scalability and expensive fees concerns, the Ethereum mainnet doesn’t seem a feasible infrastructure to support housing organizations.

We belive that this research will provide realistic feedback on using aragon on existing social problems. 

### Solution

Our motto is house-the-unhoused. We will provide a user friendly toolbox for the self-organization of common resources of buildings. Because of the knowledge gap between average people and blockchain technologies we don’t think a universal proposal to housing problems will succeed. That’s why our project is focused on an intensive field work with different entities of the Barcelona associative network, so we can set useful tutorials, workshops and strategies for an organic adoption of AragonOS by Barcelona citizens. We will also establish fluid channels of communication with Aragon App development teams so they can have a direct contact and give them real feedback from real users.

In addition, we can solve the Ethereum mainnet usability handicaps by deploying AragonOS and it’s modules into nou.network. This way we can ensure low transaction fees and solve the scalability concerns of Ethereum mainnet. By setting a root hash commits of nou.network state into the Ethereum mainnet we ensure the security of the underlying organizations in case of a nou.network shutdown event.

Kipos housing research our PROPOSAL also may profit from the features of the Aragon ecosystem.
We think that is time to do a research on applying Aragon in Barcelona on this scenario, within the following context:

- deployment in a local blockchain: even though mainnet provides a high guarantees on security and decentralization it is easier for social activists not familiar with blockchain to trust in a local network where the nodes are well known. Other problems like privacy or transaction costs are not fully solved, but these are problems that can be easily overcome.
- english is not a native language in Barcelona, and the application should be understood by locals.
- most of the Aragon functionality should be useful but writing a complementary aragonApp for a specific housing project could unlock its potential.
- onplace research with locals on how to use decentralization with aragon, as also developing new concepts should be also a priority for success.
- research on the possibility of deploying smart legal agreements for housing cooperative services with Aragon.

## Deliverables
1. Fully deploy Aragon on nou.network. nou.network is a small PoA for social projects with nodes from UPC, UAB, UOC, UdG, UIB, URV university teachers, GuifiNet and members the White Hat Group, that at this moment is also developing a project on a complementary social coin for the Sants neighbourhood in Barcelona. This also includes the required infrastructure (like ENS or aragonPM) and a basic translation to catalan and spanish of some modules. 

2. A research paper in english with the key findings on using Aragon and decentralized technologies, in housing projects, probably including: pains/gains, usage scenarios, conceptual approaches for mass adoption, next steps, and (we hope) a first real usage analysis. 

    - History and memorandum of all kipos meeting with Barcelona housing organizations. A detailed feedback from the Aragon dApp ecosystem teams.

    - A website or wiki promoting Aragon software to empower housing communities in Catalan and Spanish.

3. A specific AragonApp to manage shared resources based on the research paper on housing projects problematic created.

## Grant size

Funding

- An initial 6k€  + 6k€ in DAI, split into chunks paid out over achieved deliverables.

Success reward

- 4k€ in ANT, given out when all deliverables are ready.

## Application requirements
- Details of the team members, alongside with their willingness in terms of implication:

    - Pol Torrent (@PolTorrent): graduated in philosophy, works as a consultant for ITSCM.de and as a teacher in Blintech academy. In charge of theoretical research of the project, part-time dedication (20h/w).

    - Mariona Farell: industrial engineer, organizer of the Women in Blockchain Barcelona (WIBB) meetup, in charge of technical development of the project, part-time dedication (20h/w).

    - Adrià Massanet: Barcelona ethereum meetup organizer, lecturer on secure blockchain programming at UPC university, member of the WHG Aragon Audit team, mentor of the project, 2-3h/w dedication.

- Estimated average burn rate for completing the deliverables

    - Aragon deployment on nou.network: 1k€/mo x 1mo
    - Research paper: 2k/mo x 4mo
    - Specific AragonApp: 1k/mo x 2mo

- Legal structure to be adopted, if any

    - We will self-organize with an Aragon DAO on mainnet, we don’t want any legal structure behind us.

## Development timeline
The development timeline will be the following one in regards to each deliverable:

- Month 1 : Aragon deployment on nou.network
- Month 4 : Delivery of the research first draft
- Month 6 : Delivery of the AragonApp + final research paper

**Comment by LouisGrx** [comment]
Hey there,

Nest wouldn’t usually fund research initiatives. However, considering the broader proposal, the results of the experiment and the user feedback it could generate sound interesting.

How would you split the €12K funding among deliverables and over which conditions? Do you think you could lower this amount further or it wouldn’t make sense?

Thanks!

**Comment by bitsybloques** [comment]
Hi there Louis,

Thanks for your question.

Please note that our project isn't just a research initiative but also an integration of Aragon OS, other Aragon modules and ENS on a Ethereum based PoA Local Network ([nou.network](http://nou.network:8000/)). 
By eliminating fees and other scalability concerns of the Ethereum Mainnet we’re ensuring Aragon OS to be usable and adopted by locals, meaning that we are going to get an interesting feedback loop regarding Aragon usability, as well.

Our research will also consist in an exhaustive field work translated in numerous meetings with different housing activist collectives, housing cooperatives and squat movements in order to share with them the potential of Aragon OS and propose them to use it a logistic backbone for their resistance operations. These meetings together with the evolution of our project briefings will be posted in our Aragon Forum thread.

We think our 12k funding is actually under a market price, but we are really engaged with the Aragon project and we count with big motivation for helping to solve the housing problem in Barcelona, so we think these are fair figures for both sides: 
* **12k€ in DAI**, split into chunks paid out over achieved deliverables (there are 3 deliverables, so 12/3)
* **4k€ in ANT**, as a success reward, given out when all deliverables are ready.

**Deliverables**
1. Month 1 : Aragon deployment on nou.network (PoA).
1. Month 4 : Delivery of the research first draft.
1. Month 6 : Delivery of the AragonApp + final research paper.

Happy to hear more about your meaningful inquiries or suggestions.
Kipos Team.

**Comment by LouisGrx** [comment]
Hey again,

We’ve been discussing this proposal at length. The experiment detailed here sounds interesting and we would have expected to learn a lot given the quality of the team. Unfortunately,  funding research efforts through Nest is not obvious as we want to manage our resources in a very lean fashion and prefer to remain focused on work that has a direct impact on the rest of the network. Moreover, in this research users are a bit far from Aragon’s current potential users. For these reasons we are going to pass on this proposal.

Thank you again for your interest in Aragon and involvement in the community, it's great to have you around!

**Comment by polTorrent** [comment]
Hi,

Thanks for the update and your kind words to our team.

We’re a bit sad for your resolution because we think Aragon could have been a perfect toolbox for families and collectives struggling with the housing crisis. We still believe that’s an extremely good opportunity to increase adoption and to rethink the way we live in community and face the real estate monopolies.

But we also understand that maybe now this research doesn't fit well with Aragon’s current priorities and network needs. Furthermore, we understand that it’s difficult to do a lean and objective follow-up of this kind of ‘50% technical + 50% on-the-field research’ project. 

We hope to continue collaborating with Aragon community by other means.

Sincerely,

Kipos Team
<3 <3 <3

**Comment by LouisGrx** [comment]
Hey, 
Big thanks for your involvement in Aragon. We will close this one and wait for another occasion to collaborate.

Best
