### ISSUE TITLE
Aragon Nest Proposal: Buidl Guide for Crypto Industry.

### ISSUE THREAD

**Issue by quardz** [aragon/nest#163]
# Aragon Nest Proposal: BUIDL Guide

## Abstract

There are 1000s of crypto enthusiasts who like to contribute crypto but they are not sure how to, where to and what to contribute. On other side 100s of crypto projects needs contributions like testing, translation, writing documents and tutorials, developing plugins and lot more. Buidl guide solves this by curating contribution guidelines of all crypto projects in one place, so contributors can pick up the tasks based on their skill, projects, etc. It's live here: https://buidl.guide

So Buidl Guide will curate:
1. Contribution Guides
2. Crowdsourced Ideas for BUIDL
3. Use cases for projects

## Deliverables

1. Curate guides for Ethereum core, Dev tools, Utilities, wallets, and other infrastructure projects, etc(already done for 200+ projects, i will finish this by June).  
2. Curate all important projects like Aragon, 0x, Maker and more(By August 2019). 
3. Self-serve portal for projects to add guides(By August 2019). 
4. Reaching out contributors and projects. (This will be continuous work without a deadline)
5. Starting adding non-ethereum projects like Cosmos, Polkadot, Tezos, etc. (This will be continuous work without a deadline)

## Grant size

Funding: Total of 12000 DAI split into chunk for achieving the deliverables and running the system for the next 1 year. The fund will be mostly used to cover the servers, onboarding projects, and contributors and cover founders basic expenses. 

Success reward: Up to 30k ANT, given out when all deliverables are ready.

## Application requirements

* Plan to complete deliverables listed(1,2 and 3) above.
* Details of the team and it's commitment to the grant project
* Estimated average burn rate for completing the deliverables

## Development timeline

The development timeline will be the following one in regards to each deliverable:

1. June 2019
2. August 2019
3. August 2019
4. N/A
5. N/A

**Comment by LouisGrx** [comment]
Hey there @quardz, 

That's a cool website you are building, we also appreciate to see Aragon on there. We are currently in the process of thinking about bounties and contributor experience in Aragon ([see](https://forum.aragon.org/t/experimenting-with-bounties-using-the-projects-app/1016)). We'll probably need a bit more time to think about this while keeping your proposal in mind. Thanks for your patience!

**Comment by quardz** [comment]
Hello @LouisGrx 

Yeah, page for Aragon is here: https://buidl.guide/aragon. Need to add more Contribution Guides / Use-cases / Ideas to Aragon page. Will add in coming days or if you can give the right person to discuss this then i can compose more  Aragon Guides. 

Many thanks.

**Comment by LouisGrx** [comment]
Hey there @quardz,

As said earlier, this is initiative is a bit early for us and we need to keep working on our contributor strategies. I will close this proposal for now but we'd love to keep in touch.

Thanks again for this cool proposal.
