### ISSUE TITLE
Aragon Nest Proposal: Slingshot - Decentralized Transparent Accelerator

### ISSUE THREAD

**Issue by alonshavit** [aragon/nest#169]
# Aragon Nest Proposal: Slingshot - Decentralized Transparent Accelerator

## Abstract

[Slingshot](https://www.slinglabs.io/) is a decentralized and transparent accelerator which is manifested in both the physical world and a specially crafted DAO built on top of [Aragon](https://aragon.org/). Unlike any other accelerator, where peer-learning occurs only between the participants, Slingshot is intended to be transparent and open to all. The goal of Slingshot DAO (Slingers DAO) is to match high value projects with protocols, fund projects in a secure and transparent way and ultimately accelerate the Web3 ecosystem development and adoption.

#### **Slingshot’s Structure**

*   **Experts gild** - a small group of industry experts with the following responsibilities: vote on each batch winning team, vote on further funding of teams.
*   **Production gild** -  a small group of community managers in charge of the DAO’s physical events, community relations and electing the Experts gild.
*   **Funding**- will enable lead protocol partners (LPPs) to create recurring token contributions (based on the EIP 1337 standard, similar to [gitcoin grants](https://gitcoin.co/grants/)) to fund their chosen teams in a transparante and secured way (for both sides). 
*   **Staking** - will enable the public community to stake on the winning teams.

#### **Integration With Aragon**
Aragon apps deployed on the testnet including the UI to conveniently elect Experts, fund projects and vote for the winning teams.

## Deliverables and timeline

The development timeline regards each deliverable:

<table>
  <tr>
   <td nowrap>
    <strong>Estimated time frame</strong>
   </td>
   <td>
    <strong>Features</strong>
   </td>
  </tr>
  <tr>
   <td>
    23.6.19 - 30.6.19
   </td>
   <td>
Production gild + Experts gild -  UI and contracts implementation for authorizing and electing the Production and Experts gilds.

   </td>
  </tr>
  <tr>
   <td>
    1.7.19 - 28.7.19
   </td>
   <td>
    Voting: 
<ol>

<li>Enabling the Production gild to elect new Experts (and dispatch experts).

<li>Enabling the experts gild to vote on the winning teams during the designated time frame.
</li>
</ol>
   </td>
  </tr>
  <tr>
   <td>
    29.7.19 - 19.8.19                   
   </td>
   <td>
Funding - will enable lead protocol partners (LPPs) to create recurring token contributions to the teams of their choice with the option of filing a dispute in the case of misbehavior by a team. The dispute claim will be concluded by a vote on the Experts gild.

   </td>
  </tr>
  <tr>
   <td>
    20.8.19 - 27.8.19     
   </td>
   <td>
Putting it all together, testing and showcasing on EthBerlin - come hack with us! (<a href="https://ethberlinzwei.com/">https://ethberlinzwei.com/</a>)

   </td>
  </tr>
  <tr>
   <td>
    TBD
   </td>
   <td>
Staking - enable the public community to stake on the winning teams.

   </td>
  </tr>
</table>

## Grant size

Funding: from $50k up to $100k in ETH, split into chunks paid out over achieved deliverables. \
Success reward: Up to $50k in ANT, given out when all deliverables are ready.

**Comment by LouisGrx** [comment]
Hey @alonshavit,

Thanks a lot for your interest in the Nest program! That's an interesting project you propose here, and it even has some similarities with our very Nest program. Unfortunately, Nest's mission is to fund technologies and initiatives that will bring Aragon to its final users. As a result, while we would love to see this Accelerator DAO running, we are going to pass on this Nest proposal. 

I'm going to close this issue. We hope to see you around in the community, on the [chat](https://aragon.chat/home) and the [forum](https://forum.aragon.org/)!
