### ISSUE TITLE
Nest process clarification

### ISSUE THREAD

**Issue by john-light** [aragon/nest#173]
A comment was left on a [request for funding](https://github.com/aragon/nest/pull/164#issuecomment-495605672) that stated:

> Pull requests stand as requests for funding and are accepted only once the proposal has been discussed and feedback has been provided by the Aragon Association in the issue tab of this repo.

However in the Nest README file and associated documentation it is not clear that the applicant must wait for approval from the AA before submitting a PR with a request for funding:

![Screenshot_2019-07-10 aragon nest](https://user-images.githubusercontent.com/9424721/60954886-9a6a9500-a2b4-11e9-874a-d8be1be10202.png)

The closest I can find is this part that is in the FAQ:

> Once the proposal is approved we move to the second stage.

![Screenshot_2019-07-10 aragon nest(1)](https://user-images.githubusercontent.com/9424721/61014661-6a1b0900-a33d-11e9-9f3a-99e181ef7874.png)

If indeed this is the expectation then it should be made explicit in the instructions for applying that the Proposal For Grants (PFG/ GitHub issue) must first be approved by the AA before a Request For Funding (RFF/ GitHub pull request) is submitted. This seems like a crucial step but the closest reference to it is one not very explicit sentence buried in the FAQ.

Currently the workflow in the README is described as:

1. Create or join a proposal via issue
2. Discuss proposal
3. Create request for funding via pull request

When it actually is:

1. Create or join a proposal via issue
2. Discuss proposal
3. AA approves proposal
3. Create request for funding via pull request

Let's clear this up so applicants can feel confident applying with proposals and requests for funding 😀

**Comment by LouisGrx** [comment]
Great catch thank you @john-light. We will be watching closely at ANV#3 to see if the new [Nest DAO](https://forum.aragon.org/t/agp-proposal-for-a-new-nest-grant-allocation-process/998) is approved by ANT holders. If it is the case, it will be a great opportunity to update the process presented in the Nest repo accordingly and clarify the points you are mentioning here!

**Comment by burrrata** [comment]
Closing as we now have a new application process. Sorry that this was not addressed and implemented when it was relevant. We now have regular bi-monthly Nest infrastructure/operations meetings to ensure that we follow through things like this.
