### ISSUE TITLE
DAOs for Science And Research

### ISSUE THREAD

**Issue by soenkeba** [aragon/nest#177]
# Aragon Nest Proposal: DAOs For Research And Science

## Abstract

Science and technology research is of high relevance for us all. Just like every other endeavor it needs resources, money and ways to distribute those resources.
Science funding distribution and governance is a complex system with many different stakeholders and participants. Its current system grew over many decades and, just like in many other legacy systems, we see many media breaches and disruptions of coherent work flows, double efforts in budget planning and accounting, obscure decision making processes, etc.. This proposal evaluates the great opportunity of blockchain technology and Distributed Autonomous Organisations (DAOs) to substantially improve to restructure those processes.

### However, some developments specific to science are especially troublesome:

Research grant applications involve significant resources by the applicants which are often wasted due to massive oversubscription. Some studies even show that the efforts spent on grant writing outweigh the money that is actually distributed throughout the particular grant program. “The grant proposal system compels researchers to devote substantial time to writing proposals that could have instead been used to do science. [...] the value of the science that researchers forgo while preparing proposals can approach or exceed the value of the science that the funding program supports. (https://journals.plos.org/plosbiology/article?id=10.1371%2Fjournal.pbio.3000065). In their desperate efforts to overcome this very few science funders moved to completely random lotteries to distribute money.
A high quality of grant proposals are necessary to succeed in the artificial competitions that are becoming excessively intense. Through the competition the acceptance rate of grants dropped significantly. For example: In 2000, more than 30 percent of NIH grant applications got approved. Today, it’s closer to 17 percent. "It's because of what's happened in the last 12 years that young scientists in particular are feeling such a squeeze," NIH Director Francis Collins said at the Milken Global Conference in May (https://www.vox.com/2016/7/14/12016710/science-challeges-research-funding-peer-review-process). Some research institutes outsourced the grant writing efforts to companies, marketing professionals, etc. which get paid significant shares of the research money which could otherwise go into science.
The administrative processes on the funding side as well on the side of the research institutes is humongous “Therefore, a large portion of the research money is just used to maintain this bureaucracy. Already in 1997, the European Court of Auditors criticized the EU in relation to the 4th Research Program as an “enormous bureaucracy and a useless waste of money” (https://link.springer.com/chapter/10.1007/978-3-319-00026-8_3).
On top the actual decisions making processes on which grant proposal succeeds are obscure, hampered by network effects, informal social networks and lead to funding of projects that support current narratives instead of really innovative research. e.g.: “(…) The findings suggest that the competitive project selection procedure is less receptive to novel ideas from researchers with low academic status and therefore discourages their novel research.“ (https://www.sciencedirect.com/science/article/abs/pii/S0048733318300726)

### DAOs and blockchain could help on many levels:

Decreasing bureaucracy: Since value transfers and transparent audits are natively supported, DAOs could replace tedious accounting processes. The immutable trace of how research money was allocated and spent could not only lead to tremendous cost savings but also uncover unfair or fraudulent allocation of funds, while complying with necessary requirements e.g. on transparency.
DAOs allow flexible and slim decision-making processes and governance mechanisms. The modular architecture of Aragon provides a toolbox of essential, like the voting and the finance app, and allows infinite room for experimentation with new governance mechanisms or additional modules.
DAOs are not only capable of reorganizing funding processes on the micro level (project resource spending), but also on a macro level (grant distribution). The latter comes with enormous requirements on performance and security, since the macro case involves complex decision-making processes, vast stakeholder maps and potentially huge amounts of funding. Yet, since they allocate funds presumably more efficiently and wisely, DAOs for the macro case could have a substantial effect on scientific progresss as a whole.
Continuous funding and publication methods could merge the efforts of publication writing and money distribution - a publication can become a grant application and vice versa (e.g. the abstract machine on Pando).
DAOs as rethinking organizations can organize research projects across the borders of traditional institutes and could therefore improve goal-driven research over institute based research. DAOs can even serve as a neutral technology that resides in its own Aragon jurisdiction, avoiding political influence and bias on science funding.
The specific problem that we want to solve: Paving the way to deploy real DAOs where there is a need, namely in science funding and publishing.
Since Blockchain and DAOs are still a rather recent phenomenon and novel concept, the intersection of people who both understand the potential of blockchain and DAOs and engage in scientific work or science funding is still very small. We tackled this successfully through meetings (www.blockchainforscience.com), publications (https://www.blockchainforscience.com/2017/02/23/blockchain-for-open-science-the-living-document/) and conferences (www.blockchainforsciencecon.com), and this is just the beginning. There is a long roadmap ahead and many problems to be solved before we can get to deploying DAOs in science, particularly conceptual questions as well as legal/fiscal questions only scratched the surface. By involving real researchers in real research institutes in a DAO experiment, our goal is to approach this ambitious project iteratively. We intend to do so by learning through piloting a DAO and raising more awareness by publishing scientific publications about the process of doing so. As a result, we gather essential know-how on how DAOs can solve problems in science and thereby pave the way for a cambrian explosion of DAOs and decentralization in the world of science.

### Deliverable 1:

One research project organized with an Aragon-DAO in real research institutes with a specific research question:
After setting up 10 researchers with the necessary knowledge about DAOs, wallets, etc. we will test transactions on a test net. The researchers will vote on how the money is being spent on a per task basis.
After the initial (test net) phase, we define a specific research project and organize it through an Aragon-DAO that will be topped of with 30.000 \$ worth of DAI. This could be extended to two research projects in two different fields.
Through our efforts over the last two years we have identified a numberof researchers who are interested and qualified in getting involved. Specific names and projects can be disclosed on request and will be announced during the process.
Funding necessary: 30k of DAI per research project organized by a DAO, 20k for personal expenses for work package, education of researchers, travelling.

### Deliverable 2:

Evaluating barriers to adoption and testing the ‘as is’ technology stack of Aragon with researchers as lead-users in realistic settings in order to provide detailed, context-specific feedback on conceptual requirements and usability issues.
We will write blog posts and a scientific article about the process and present at conferences and to funding agencies.
Funding necessary: 20k worth of DAI for work package, personal expenses, travelling and publishing

### Deliverable 3:

We will evaluate what specific functionalities and additional modules should be included into the Aragon ecosystem in order to make Aragon DAOs the default choice in the research world with appropriate out-of-the-box functionalities. We will propose a future roadmap and an ecosystem analysis to define interfaces with other projects that will support other aspects of the scientific conduct, such as publishing through Pando, incentivation through cryptoeconomic models or else.
Funding necessary: 5k worth of DAI for personal expenses, working with developers and specifying functionalities.

Success reward:
Up to 20k ANT, for finishing the research project (s), a research paper about DAOs in research in a reputable science journal, blogposts and How-Tos aimed at researchers to adopt DAOs with specific solutions to administration and taxation and 3 presentations at reputable international science conferences.

## Application requirements

- Two real world research insitutes (already approached)
- Two research projects that will be organized using a DAO
- Legal structure exists (e.g. Blockchain For Science GmbH, or research institutes)
- Team that conducts the project exists

## Development timeline

2 month: Finding and educating researchers, defining the DAO organized research projects(s), doing mocku-up science projects on the testnet, webpage
6 month: Setting up topped up DAO(s) and performing the research project(s) organized through the aragon DAO(s)
4 month: Publications and presentations, How-Tos, working with developers

**Comment by LouisGrx** [comment]
Hey there, Thanks a lot for your interest in Aragon DAOs and patience. 

We will unfortunately have to pass on this proposal. While research is a use-case we would love to cover with Aragon Organizations, the Nest program is not focused on granting money for user research or experimentation at this time. Some of our teams do provide assistance in discovering and using Aragon DAOs however. Let us know if you are interested in getting in touch with them!

The Nest team
