### ISSUE TITLE
Aragon Nest Proposal: DAO Bank / Investment fund

### ISSUE THREAD

**Issue by leolower** [aragon/nest#178]
# Aragon Nest Proposal: DAO Bank
We would like to present this idea, which is in an early stage, in order to gather feedback from the community and refine it as needed. 
We are aware that other alternatives are under development at the moment but we also truly believe this proposal has a different value proposition that could appeal to  different types of users, even new DAOs could be created as an outcome of this proposal.

## Abstract

DAO Bank is an investment / fund management app which integrates and connects with different open and decentralized lending and staking protocols such as dyDx, Compound, Uniswap, Dharma, Fulcrum and Livepeer, Decred, Loom, among others.

This application will **help fund managers research, select and create investment strategies based on information provided by the app to get the best possible return** (e.g.: APR, yield). The information will be retrieved in real time from the protocols smart contracts. 
The user will be able to see and filter options based on the DAO’s available fund, assets, and the protocols features and constraints such as instant withdraw, lockup time, KYCed/anonymous investment, etc.

As a user creates an investment strategy, it can either be directly executed or go through a vote, depending on how the app has been configured and the user permissions.

By suggesting in real time **the best possible investment** (among a set of selected investment protocols), this application will help in the creation of investment strategies that can be based on current or historical data, given that all this information is publicly available in Ethereum.

Possibly, the strategy execution could leverage existing apps already integrated with the DAO through the Aragon Agent, but in order to standardize data and make intelligent comparisons, each investment platform will require some customization in the App’s UI.

Future potential features of this App could also include reputation tokens that are used for earnings distribution and complex strategies involving 2 or more investment platforms and preset periods of time. The possibilities are endless.

### An example
For example, let’s suppose that the DAO holds MakerDAO DAI stable coin and a DAO member wants to propose an investment in a lending protocol based on APR which allows instant withdraw. Let’s also suppose that the app is connected to 
Compound and dYdX. The workflow would look like this:

1 - The user will go the the app and select to invest in __Lending__.
2 - The user will set the filters to ‘APR’ and ‘instant withdraw’.
3 - The app will show Compound and dYdX and their current APRs.
4 - The protocol with the highest APR will be selected.
5 - The user will set the amount of DAI to invest and perform the ‘Invest’ action.
6 - The app will interact with compound and do the investment.

At any moment the protocol’s APRs could change and the investment no longer be the most beneficial. In this case, a user will be able to ‘rebalance’ the investment and the app will withdraw the funds from Compound and invest in dYdX.
The rebalancing mechanism could be executed by an oracle or a DAO member.

### Who would use this
Although any type of DAO could take advantage of the investment strategy suggestions and standardized investment view, we believe these would benefit the most:

- Any DAO with spare or idle funds who would like to get a passive income.
- New DAOs that function as investment funds.

Some initial wireframes and technical specifications can be found [here](https://docs.google.com/document/d/1DP-4o1ODme2sxnO2jroynKe2v_NRqi3DaxcPyqDTqV4/edit).

## Deliverables
1. Investment platforms comparison view with real-time information
2. Investment strategy creation and management
3. Investment strategy execution through Aragon Agent
## Grant size

Funding: TBD
Success reward: TBD

## Application requirements
- TBD
## Development timeline
1. TBD

## Next Steps
1. Gather community feedback (1 to 2 weeks)
2. Create a detailed proposal (scope of work, time estimates, roadmap, grant size, etc)

**Comment by stefanobernardi** [comment]
Thanks so much for this proposal, I think that DeFi <> DAOs is one of the most interesting spaces to play in and explore.

That being said, I'm not 100% sure that developing some complicated tooling or even specific investment strategies is the right way to approach this - and especially not the right thing to fund for the Aragon Nest program, as it's not something that would massively benefit the rest of the community.

The DeFi space moves so fast, and we still don't have an easy way for investors to pool capital together and handle it in a decentralized, uncensorable and trustless way - so in my view that is the biggest opportunity here.

I think that if you could come up with a proposal along these ideas, so trying to build apps or infrastructure to better help DAOs interact with DeFi products and attract more capital to the space, it could be a really solid direction.

**Comment by leolower** [comment]
Thanks for the feedback @stefanobernardi, we really appreciate it and we'll think about it.
