### ISSUE TITLE
Fan-driven Bounties for Creators

### ISSUE THREAD

**Issue by jatinshah** [aragon/nest#184]
# Aragon Nest Proposal: Fan-driven Bounties for Creators

## Abstract

Crowdfunding is a popular and well-established method for creators to raise funding from their fans for their projects. There are many successful centralized crowdfunding platforms like Kickstarter. There are also a few decentralized crowdfunding platforms including Aragon Fundraising (previously called Apiary). However, top creators often do not prefer using crowdfunding platforms. The main reason is that most crowdfunding platforms do not reach their target funding goals. Creators do not want to be associated with such projects and risk loss of reputation.

At the same time, with the rise of live streaming platforms like Twitch, there is an emerging trend of fans setting bounties for their favorite creators. These bounties can be unlocked when creators complete a specific task. We want to extend this behavior to fans active on platforms like DeviantArt & Pixiv (for illustrators), Twitcasting (for live streamers) and Patreon.

Specifically within the anime & manga community, we believe bounties can be used by fans to request:
- A new chapter of a manga 
- A manga title to be made into an anime film
- Reboot of a popular anime title
- New season for a popular anime title
- Subtitling and dubbing for an anime film
- Cosplayer to dress up as a popular anime character
- Merchandise for a specific title or a character
- AMA with a creator or talent of a popular anime series

Hence, we want to propose a decentralized platform on Aragon for fans to create and fund bounties for their favorite creators. Building such a platform on decentralized stack has several benefits:
- Fans across the world can define bounties and stake ETH without using traditional electronic payment networks
- Unlike fiat currencies, holding assets like ETH for extended duration does not require expensive regulatory compliance 
- Building sophisticated logic for releasing ETH to creators when certain criteria are met or through a democratic vote is a lot easier to build on Ethereum than a traditional Web2.0 stack.

Fans contribute ETH, DAI or any ERC-20 token and receive an ERC-721 compliant non-fungible token (NFT) representing their contribution. As is common on creator patronage platforms like Patreon and Kickstarter, different contribution tiers are linked to different types of NFTs with different privileges. For example, certain types of NFTs may have voting privileges or access to special extras or right to make derivative works. 

Our proposed implementation, to be described in detail later, consists of three types of contract: 
- **Non-fungible token (NFT) contract**: Fan receive NFTs for their contributions. Fans are entitled to special privileges and rights based on the type of non-fungible token they own.
- **Voting contract**: Enables contributors to vote on various proposals regarding the bounty based on the type of non-fungible token they hold.
- **Bounties contract**: Manage creation of bounties, setting rewards, approval of creators, confirmation of bounty completion and disbursement of rewards.

Our implementation of the voting contract would be similar to the existing Aragon voting contract with the exception that voters will be holding ERC-721 compliant NFTs, not ERC-20 tokens. We expect it to be usable for any use case where token holders own ERC-721 tokens, not just to the specific use case of creator bounties described in this proposal. 

## Bounty Contract
In this section, we describe the key features of our bounty contract. We plan to use this contract in building a community for anime fans to create bounties for creators in the anime industry. However, our implementation of the bounty contract will be general enough that other developers would be able to use it to build a similar platform for other creators.

The key features of the bounty contract are:
- Any fan can create a bounty contract by providing description, deliverables, deadline, reward amount and reward payment terms. 
- The bounty contract can be integrated with a DEFI liquidity pool like Compound to automatically generate interest on all the contributions. 
- Fans receive a ERC-721 compliant NFT after contribution. Based on contribution tier, fans can receive different types of NFTs with different privileges and rights. For example, certain contributors may have voting rights on various decisions about the bounty or access to special extras or specific intellectual property rights over the creation (like right to create derivative works). 
- Bounties can be for a specific creator, invitation-only or open for any creator. The latter two are subject to approval by eligible contributors and controlled by the voting contract. 
- Creators can accept or reject a bounty. Creators can also accept a bounty subject to modifications that could include a demand for a higher reward amount. Contributors will be required to vote to reapprove bounties in such cases. 
- After completion of bounties, eligible creators can vote to decide if the bounty was completed successfully and whether the reward should be released to the creator. 
- Optionally, prior to accepting the bounty, creator can also propose independent judges for such evaluation, subject to approval of eligible contributors.
- At any stage during the bounty, eligible contributors can also vote to kill the bounty or replace the creator. 
- Creators can record digital or physical deliverables as NFTs on blockchain

## Deliverables

1. Voting contract: AragonOS-compatible voting contract for NFT token holders similar with functionality similar to the existing Aragon voting contract
2. Bounties contract: AragonOS-compatible implementation of Bounty contract that allows fans to create bounties for creators, and creators to earn ETH or other ERC-20 tokens by completing them
3. Anime Creator-Fan DAO: Website for creators & fans interested in anime to create various bounties. We have given some examples of such bounties earlier in this proposal 

## Timeline
The timeline below is tentative and subject to changes in the final application
### Month 1
- Final specification for voting contract & bounties contract
- Early wireframes of website for anime fans to set bounties for creators from anime industry
### Month 2
- Voting contract for NFT token holders
- Final high-fidelity mockups for anime creator-fan DAO
### Month 3
 - Bounties contract
 - Private beta of website for anime fans to set bounties for creators from anime industry
### Month 4
 - Public beta of website for anime fans to set bounties for creators from anime industry

## Grant size
Funding: Up to $150k in DAI, split into chunks paid out over achieved deliverables.

Success reward: Up to 30k ANT, given out when all deliverables are ready.

## Application requirements

- Draft specification of voting contract, bounties contract and product requirements document for anime creator-fan DAO website.
- Details of team members and their specific commitment to the project
- Detailed budget for the entire project
- Legal structure with IP-ownership details. (Smart contracts will be open-source and released under a permissive software license)

**Comment by burrrata** [comment]
This is really cool, but it sounds kind of like [Autark's bounties app](https://www.autark.xyz/apps).

[1Hive](https://1hive.org/) actually already uses bounties for our DAO's HONEY token and it allows anyone (community members) to stake tokens to an open Issue. Then BEEs (members of the the 1Hive org) can work on the bounty to earn HONEY. 1Hive BEEs can also stake HONEY to bounties for community members to work on. Throughout the process there are checks and balances where whoever created the bounty and staked tokens can approve or reject applications to work on it, and then verify that the work is satisfactory before distributing the bounty. If there was a dispute it could be resolved with the [Aragon Court](https://github.com/aragon/aragon-court).

Is this more or less similar to what you're thinking of, or are there key features of your proposal that would be different?

**Comment by LouisGrx** [comment]
Hey @jatinshah,

Thanks for your interest in building on Aragon :)

As @burrrata says above it looks like the bounty functionalities of Autark's project app would do the job for what you are proposing. 

Also the I am not sure that the Nest program is there to fund user initiatives. Fan-driven bounties for creators looks like an awesome use-case for Aragon DAOs and I would personnally love to see that implemented, but the funds of the Nest program can hardly fund all the cool things Aragon users want to build.

**Comment by burrrata** [comment]
Closing this application due to the lack of response and similar functionality of current Aragon applications.
