### ISSUE TITLE
P2P Project Management application and data storage with Dat

### ISSUE THREAD

**Issue by waldercong** [aragon/nest#19]
_See the [Guide for submitting a proposal for grants](https://wiki.aragon.one/nest/guides/guide_for_submitting_a_request_for_funding/) for further details on submitting a grant proposal_

# Aragon Nest Proposal: P2P Project Management application and data storage using the [dat protocol](https://github.com/datproject)

## Abstract

IPFS gets a lot of of love in decentralized application architecture stacks for dapps because it's a P2P storage protocol with baked in immutability.  By storing an IPFS hash for a file on-chain, a smart contract or DAO can prove that a resource was stored at a specific point in time and that the data in the resource has not changed since then.

This works great if trying to store files that you don't want to change, or serve client-side resources for a dapp.

However, in a decentralized development environment with remote contributors working together to produce or run a dapp or DAO, the assets, repository, contributors, goals, and overall state of the project is likely to change and evolve over time, which is difficult for IPFS to model without a lot of work around features.  Subsequently, data belonging to the DAO may be forced to live in and utilize centralized storage methodologies for project management (i.e. GitHub, DropBox, AWS, local storage etc.), which is not always ideal, and may be lost if the owner of the storage disappears.

To remedy, using a P2P storage protocol that can handle and sync an entire file system, monitor changes, store changes immutably, and prove those changes if necessary would be useful in coordinating a DAO and especially dapp development.

The [Dat Protocol](https://docs.datproject.org/security) works by building a merkle tree from all files in a given folder system and encrypting with a private/public key pair.  The public key is then used to encrypt/decrypt data transmitted to peers.  Peers can host the file system, but can't change it without changing the public key, but a private key owner can update the file system by using her private key to make updates without having to switch to a new public key (like IPFS).

When data is added or changed, the additions are appended and added to the merkle tree.  This makes it so the meta data in a .dat (e.g. change log) can be used to prove data changes from a data owner for a set of files because the private key needs to be used to update the .dat folder.

Dat folders can be structured to run on top of each other and inherit each other as well, which would be super useful for DAO organization and data policies.

**Here's a long-ish example story to illustrate the properties:**

- Pierre, Brett, Luis, and Calder are coordinating to develop an operating system for Dapps with DAO management features.
- Their project was funded by an ICO and governed by a DAO.
- The DAO creates 3 folders using the Dat protocol, (Dev, Prod, and Public), which each have public keys.
- Pierre, Brett, Luis, and Calder each create Dat folders, and register their public keys to the DAO's smart contract.
- The DAO's dev folder listens to changes in their Dat folders.
- The DAO's dev folder contains a git repo, which can be pushed and pulled to.
- Pierre creates a logo for the project and stores it in his Dat folder.  The logo is distributed over the dat protocol, and is held in the Dev folder, and each contributors' folders.
- Brett writes a module for the dapp and stores it in his Dat folder.  The files are replicated everywhere.  He pushes the module to the git repo.
- Calder is responsible for UX and marketing.  He decides to offer a bounty to the public for UX concepts through a smart contract.
- Jack and Jill are both UX designers.  They both register a new Dat folder to the bounty contract, and Calder and the DAO's dat folders listen to them.
- Jack and Jill produce and iterate on designs with feedback from the team and the interested DAO members.  Each iteration is tracked, changed, and backed up historically by every peer listening to the Dat structure.
- Jack tries to claim the bounty on acceptance of the last design.  But the winning design was originally created by Jill, which she can prove by referencing her .dat file.
- As the dapp comes together, the DAO votes on whether or not to release it.  When it becomes ready, the DAO copies the /dist sub-folder from Dev to Prod.
- The prod .dat can be accessed by the public, but not modified.
- The dapp can now be accessed over HTTP, but served by peers listening to the DAO/prod folder.
- 2 days later, a critical bug is found.  Luis writes a patch and pushes it to the Prod folder.  The change is recorded in the .dat, and the fix is pushed live to all connected peers.
- In the course of running the dapp, Calder writes a storage monitoring service that records smart contract storage changes and converts hex to data types before storing the history in a CSV.  He creates a script for the process to monitor his node and save historical CSVs in his Dat folder, which is listened to by the DAO's public Dat folder.
- Luis thinks the data could be mined and made useful, but doesn't have time to properly analyze it.  Instead, he creates an ETL process to take the CSVs and ingest the data into an Elastisearch database, exposing an API.
- Calder and Luis create a new bounty for a data scientist to create a dashboard on the metrics in a smart contract.
- Kyle and Kayla are data scientists, and each register dat folders to the smart contract.
- Kyle creates a WebGL data visualization tool that lets users travel through the data in VR from Elastisearch queries.
- Kayla creates a dashboard using R directly from the raw CSVs and keeps the repo in her Dat folder, which is listened to by the DAO's Dat folders.
- Calder compiles and links to both interfaces in his summary report to the DAO stakeholders.

**In all cases:**

1. "Who" is working/contributing is recorded immutably (reduces attribution conflicts).
2. "What" they did is stored on all peers (reduces risk of asset loss).
3. "How" things were changed is stored on all peers, and recorded immutably.

**Benefits:**

- Creates a flexible shared data and file system for the DAO with controls on who can change what.
- Continuous delivery over a P2P protocol  without requiring changing the resource address (like in IPFS), or providing a new checksum (like in torrents).
- The DAO owns and stores its own data and files.
- Creates a P2P version of Git and Dropbox, tied to a DAO, and manage-able via smart contract.
- File delivery (especially for large data sets) can be much faster (i.e. over UDP).
- Allows the DAO to solicit help and serve files to other entities when necessary.

## Deliverables

1. An AragonOS compatible desktop dapp that can install the dat protocol dependencies, listen to other dats in a DAO, serve dats as a peer, and associate dat public keys to DAO smart contracts.
2. A DAO dat server web application that exposes the git API, manage a dat folder system, and serve dat files over http from a URL.
3. A project management UI and smart contract template for associating and structuring dat folders/contributors with relevant tasks and escrow funding.

## Grant size

Funding: Up to $100k in ETH, split into chunks paid out over achieved deliverables.

Success reward: Up to $50k in ANT, given out when all deliverables are ready.

## Application requirements

- Project plan, specification overview, and and task list.
- Details of the team members, alongside with their willingness in terms of implication
- Estimated average burn rate for completing the deliverables
- Legal structure to be adopted, if any

## Development timeline (estimates)

The development timeline will be the following one in regards to each deliverable:

X = Proposal Acceptance

1. X + 2 weeks: Project plan, specs, task list, and resource schedule/calendar.
2. X + 4 weeks: Plan reviewed and accepted.
3. X + 12 weeks: Dat/Dapp web app/server and file system.
4. X + 16 weeks: Local Dat/DAO node desktop build (electron).
5. X + 20 weeks: Smart Contract/Dat interactivity for identity/folders/files.
6. X + 24 weeks: Project Management UI tying it all together.

**Comment by mariapao** [comment]
Hi @waldercong just in case, your proposal was approved a few days ago. The next step is for you submit your application. Make sure you follow[ these ](https://github.com/aragon/nest/blob/master/README.md)instructions 

We are looking forward to seeing your application! Feel free to ask any questions you may have about the application process :)

**Comment by chris-remus** [comment]
I'll be following this one in particular. The project management angle interests me quite a bit.

**Comment by waldercong** [comment]
@mariapao sorry I'm late on sending in a plan--we got slammed with a last minute project, so I'm trying to make sure I can allocate the correct amount of bandwidth over the next few months to get this done.  @chris-remus yes, absolutely envision a task management component, preferably out of the gate.  Ideally, this would be able to take over the majority of what a GitHub/Asana does in a decentralized working and managed environment.

**Comment by mariapao** [comment]
I'm closing this proposal as there is a Flock team (Autark) that is working on a similar [initiative](https://github.com/aragon/flock/blob/master/teams/Autark/2019Q1-2.md#i05---data-storage-and-standards)
