### ISSUE TITLE
Security or Equity token user interface for detailed information access

### ISSUE THREAD

**Issue by mfppvl** [aragon/nest#191]
# Aragon Nest Proposal: Security or Equity token user interface for detailed information access 
## Abstract
The Security and Equity asset-backed tokens all are compatible with ERC-20 wallets, but as of today evolved beyond basic ERC-20 token. Modern-day asset-backed tokens have advanced functionality like time locks, vesting schedule and carry more information like issuer incorporation details, links to articles of organization, etc., but standard ERC-20 wallet doesn’t provide access to this information that leads to frustration for token holders (end-user). Development smart contract data reader will provide easy one-click data access to all plus seamless integration for the developers.
 

1. “Auto-generation of the user interface on ABI upload” research and design principals and guidelines for ABI generated user interface by token issuer. With the option to reorder functions like companyName, incDate (date of incorporation), incCountry (country of incorporation), etc. to make easy accessible and readable for end-user in addition to balanceOf, token name, symbol and similar.
2. “Front-end Web3 library” Develop a library to make it easy for developers to add to it to the front-end to provide end-user with information that they can’t in their standard ERC-20 wallet. Allow auto-generated interface of uploaded ABI, custom reorder of available functions and hide/display function based on developer preference.

## Possible connections with 3 other proposals for grants

- [Aragon Nest Proposal: Web3 Design System The "Web3 Design System"](https://github.com/aragon/nest/issues/73) project proposes to create open-source tools to accelerate the adoption and development of the distributed web and user-friendly experiences, through the following elements.
- [Aragon Nest Proposal: radspec a tool for making Ethereum transactions readable](https://github.com/aragon/nest/issues/58): making transactions readable is a UX problem that has already been manifested by the community and Radspec as a tool will be taken into consideration and probably extended with other tools that the content designer and front-end developer can control even after the smart contracts are deployed
- [Aragon Nest proposal: DAOs and the interaction with the physical world ](https://github.com/aragon/nest/issues/48): our group doesn’t have yet a legal structure and we were thinking of creating an open organization, a Design Dao, that can receive grants and emit invoices in the real world and allow various designers to associate with the group and produce their projects via the open participation in the Design Dao itself.

## Deliverables
1. Research UI/UX design option 
  * Interview designers and developers in the space
  * Document current workarounds, proposed solutions and designs.
2. Product full specs documentation
  * Based on step 1 create development documentation
  * Create mockups and final designs
3. Develop a JS library that can be used by developers
4. Technical documentation on how to use the library.

## Grant size
Per your NEST guidelines, we are asking for 120,000 $ in ETH for operative costs of the research and development split into chunks paid out by milestones.

## Application requirements
* Details of the team members, alongside with their willingness in terms of implication
* The estimated average burn rate for completing the deliverables
* Legal structure to be adopted, if any
* Where it all started: Delaware blockchain initiative 
  * https://legis.delaware.gov/json/BillDetail/GenerateHtmlDocument?legislationId=25730&legislationTypeId=1&docTypeId=2&legislationName=SB69
  * https://www.forbes.com/sites/groupthink/2017/09/20/why-the-delaware-blockchain-initiative-matters-to-all-dealmakers/#243a1db97550
  * https://github.com/ethereum/EIPs/blob/master/EIPS/eip-884.md
  * Token lock-up periods: https://medium.com/@Priority_Token/priority-token-guide-to-an-sto-token-lock-up-period-2b59833adeed
UI/UX as a barrier for blockchain mass adoption:
https://medium.com/totle/why-crypto-needs-better-ui-ux-to-reach-mass-adoption-49ef2fb94f01

## Development timeline
The development timeline will be the following one in regards to each deliverable:
 
1. Jan 2020 Research UI/UX design option
2. Feb 2020 Product full specs documentation
3. May 2020 Develop a JS library that can be used by developers
4. June 2020 Technical documentation

**Comment by burrrata** [comment]
This is really cool. At the moment, however, the Nest program does not fund research. The [CFDAO](https://forum.aragon.org/t/how-to-make-proposals-to-the-community-funding-dao/697) can support research related initiatives.

Furthermore, this seems like a project that would benefit the entire Ethereum community. As such, the [Ethereum Foundation grants program](https://blog.ethereum.org/2018/10/24/how-the-ethereum-foundation-grants-program-makes-decisions/) might be a good fit.

**Comment by mfppvl** [comment]
Hi @burrrata, thank you for your quick reply and advice.
