### ISSUE TITLE
Aragon Chat

### ISSUE THREAD

**Issue by OKDuncan** [aragon/nest#193]
# Aragon Chat

The feature set asked for in [this grant](https://github.com/aragon/nest/issues/189) could be applied to the proposal below. This would change the scope of the current project and require more resources.

## About

Aragon Chat

Project description
The scope of this project involves creating a cryptonative chat specifically tailored to fit the Aragon community. Through this interface community members will be able to access their account functionality via a custom chat room. Essentially a command line interface for interacting with the DAO... but a chat-line interface.

Relavent Links
[Rocketchat website](https://rocket.chat)
[Nodered](https://nodered.org)
[Abridged](https://abridged.io)
<br>

## Abstract

The project will provide for an intuitive chat interface with a variety of beneficial features (which will be rolled out over time):

* Bot onboarding flow
* Access to account details
* Sending funds
* Voting and proposal submission
* Linking with Trello, sheets, flock, and PM tools

This access is designed for more seamless comms via both web and mobile. The tools provided by the Aragon Chat will result in a novel experience for members to participate in the community. Each DAO will be able to take control of their specific onboarding flow to suit their mission. Bots can be created using a visual development environment, allowing for each community to command a unique experience for their members.

This grant will allow for the team to utilize features, such as voting, proposal creation, and other DAO-related functions link directly to the Aragon contracts. Assuming the architecture is compatible, the integration will also allow for voting via L2, which means feeless and instant processing for the community. 
<br>

## Funding

All payment requested to be in DAI or ANT

$15K
$7.5K up front 
$7.5K upon completion
$10K success reward
<br>

## Roadmap

Aragon chat (using Rocketchat) with NodeRed access to add/modify features and flows. This funding will provide for a preliminary iteration of the chat interface with functionality such as submitting proposals/polls, voting, token permissioned rooms, and sending funds. The chat platform also allows for many integrations with a variety of web tools (Trello, Google Suite, Github, etc.). There will need to be further proposals and design sprints to refine and continue lowering the friction for engagement with DAO members.

Deliverables
* Scope Aragon contract integration (define possibility for L2, as well as critical functions to integrate into NodeRed/AragonChat) 
* Integrate Voting/Proposal Submission via chat 
* Create tutorial for NodeRed bot management 
* Assist in modifying bot functionality for each DAO

The Aragon chatroom implementation will go through a series of sprints to be completed in February next year. We will come out with an initial prototype by mid to late Jan, gather feedback in the weeks following, and complete a V1 iteration by February 14th.
<br>

## Team

James Young comes from a deep background in web2 gaming development. Since entering the web3 space he assisted with the AdChain TCR, was head of engineering at Spankchain, and built the Moloch DAO contracts. He comes with a wealth of background and prioritizes shipping with great user experience.

James Duncan worked on the Ethereum grants program for 8 months in 2018. There he gathered a sense of the front edge of development for the ecosystem. Since James has been focused on both decentralized governance, and most recently with Abridged, UX design.

Eric Chung discovered Ethereum in 2016 and learned how to write smart contracts in early 2017. He’s pushed technical blockchain education as a faculty member at USC and founded a coding bootcamp, DApperNetwork. He is convinced that the decentralization of features should be positively correlated to a user’s comfort with web 3, and is working to make this design pattern applicable by any developer for their dapp through his current startup, Abridged.

**Comment by pythonpete32** [comment]
Hey @OKDuncan,
Thanks for submitting this proposal. Looking at better ways for communities to interact with Aragon DAOs is a priority for us. There is also some similarity with the [MEGS proposal](https://github.com/aragon/nest/issues/190) which is currently in the review stage

A few preliminary questions that spring to mind
> The scope of this project involves creating a cryptonative chat specifically tailored to fit the Aragon community. Through this interface community members will be able to access their account functionality via a custom chat room.

Am I right in thinking this is a bot that integrates with rocket chat as opposed to a fork of rocket chat its self?

Related to this, would this be limited to rocket chat? Could this be deployed to discord or other group messaging services?

On the interface, would this be analogous to interacting with the aragonCLI but in a chat console?

> Assuming the architecture is compatible, the integration will also allow for voting via L2, which means feeless and instant processing for the community.

This is very interesting, is this within the scope of your current proposal? And if not possible would you be willing to lower the amount you are currently asking for?

Finally on the success reward. We typically do not like to fund deals solely in DAI. Flock graduates are very valuable to Aragon, we like to keep them in the ecosystem. The ANT reward is meat to give a sense of ownership over the platform they are helping to create

**Comment by OKDuncan** [comment]
Hey Aaron, thanks for your comments / interest. There is some some similarity with the MEGS proposal. We could actually incorporate some of the features from MEGS into the function options through the chat interface.

> Am I right in thinking this is a bot that integrates with rocket chat as opposed to a fork of rocket chat its self?

We do not to fork in order to take advantage of future updates. Instead we add the Abridged toolkit and deploy that.

> 
> Related to this, would this be limited to rocket chat? Could this be deployed to discord or other group messaging services?

Not necessarily limited to Rocketchat. The functionality could be created for other messaging services, as long as their frontend is open sourced, or they are willing to incorporate the SDK.

> 
> On the interface, would this be analogous to interacting with the aragonCLI but in a chat console?
> 

Would need to answer this in the first deliverable when we investigate the ideal functions to be accessed.

> This is very interesting, is this within the scope of your current proposal? And if not possible would you be willing to lower the amount you are currently asking for?

This is in the current scope.

> 
> Finally on the success reward. We typically do not like to fund deals solely in DAI. Flock graduates are very valuable to Aragon, we like to keep them in the ecosystem. The ANT reward is meat to give a sense of ownership over the platform they are helping to create

Understood, we're willing to accept both! Updated the reward.

**Comment by burrrata** [comment]
This is interesting. 

Quick non-interesting question: what's the difference between the 7.5k upon completion and the 10k success reward? Wouldn't those both be paid upon successful completion?

**Comment by OKDuncan** [comment]
Hi burrrata,

TBH, I am unfamiliar with success reward system for Aragon in other projects. I'd leave it up to a  vote by the community whether the reward is deserved at the end.
