### ISSUE TITLE
Finch West Project Proposal

### ISSUE THREAD

**Issue by Finchwest** [aragon/nest#195]
# Finch West Project Proposal

Detailed project proposal attached: 
[Finch West Project Proposal v0.09 (updated 11.22.2019).pdf](https://github.com/aragon/nest/files/3901935/Finch.West.Project.Proposal.v0.09.updated.11.22.2019.pdf)

<br>

## About

**Project name:** 
Finch West

**Project description** 
- The Finch West project aims to build four guilds on the upcoming Ember Sword blockchain game, which will include video game assets (cosmetics and emotes) and ownership of land within the game
- These guilds will function as decentralized organizations, which will take advantage of the Aragon platform 

**Where did you hear about the Nest program and what prompted you to apply?:**
Our project requires the use of decentralized organizations. Our search for the appropriate blockchain to enable our project has led us to Aragon (through a Google Search). After reviewing the Aragon website, we realized that the Nest program would be a great opportunity to fund our project, while partnering with Aragon to help us realize our vision.

<br>

## Team

**Name of the project lead:**
Mohad Ali (https://www.linkedin.com/in/mohadali/)

**Email address of the project lead (whoever is filling out this application)**
mohadali1@hotmail.com

**List each other member that is/would be working on this project (LinkedIn/GitHub profiles are preferred but not required)**
- Demetri Palmer
- Kunnal Kainth
Note: 5 others have expressed interest in participating in the project, but will be onboarded after the initial planning phase

**What are the main roles of each team member?**
The project has 8 stated roles: Project Management, Web Administration, Asset Development, World Building, Marketing Communications, Community Development, Financial Management, Partner Management

Given the current state of the project, team members have not yet been assigned to their respective roles.

**Has the team already worked together? (please provide details)**
Yes - the team has worked together closely and previously built 2 projects:
- Enthoosi: a video game market analytics dashboard (powered by Microsoft PowerBI)
- Air Combo: a video game project management tool for indie game developers (using Wordpress)

**Is your team already present on the Aragon Forum? If Yes, what are your usernames?**
Yes - recently created account (Finchwest)
<br>

## Progress

**How far along are you?**
Our project is currently in the pre-production stage. As of January 2019, we have been staying in close contact with the Ember Sword team and brainstorming our world building/cosmetic assets

**Is anyone using your product/application?**
Not yet - please see project timeline for additional details (PG 13 of the attachment)
**If yes, How many active users do you have and what kind of feedback have you received?**
N/A - however, we have received very positive feedback on the idea from other gamers
**If you've applied previously with the same idea, how much progress have you made since the last time you applied? What has changed?**
N/A - this is our first application
<br>

## Idea Problem

**Why did you pick this idea to work on? Do you have domain expertise in this area?**
In the past, our team has participated in projects that offer services to independent video game developers (Enthoosi/Air Combo). As video game and blockchain enthusiasts, our thesis is that _blockchain gaming has turned video game items into financial assets. For this reason, gamer guilds will function like decentralized organizations_

**What's new about what you're making? What do people resort to because it doesn't exist yet (or they don't know about it)?**
We're planning to build a use case for gamer guilds as decentralized organizations in blockchain MMORPGs. We are confident that this will be a model for millions of gamers in the near future and we plan to be the first public experiment.

Currently, a large market exists for gamers to buy in-game assets, but they are not able to resell them. Blockchain gaming plans to address this and our project will demonstrate the true value of blockchain gaming for MMO gamers.

**Have you talked to people about what you're making? Do people want it and do you have examples of this?**
For years, we have spoken to gamers in a variety of gaming communities (across console and PC games) to better understand the challenges developers and players are facing. We built the Finch West project to fit our analysis - blockchain gaming will fundamentally change the gaming industry and players can take part in this value creation by building guilds who act as decentralized organizations.

A clear example of guilds who would be well served by our project will be the guilds currently forming around the Ember Sword game currently in development.

<br>

## Market

**What is the target market or end user in mind for this project?**
The target market is made up of 3 groups: Ember Sword players, the overall gaming market and players in the Greater Toronto Area. For more detail, please see the attached project proposal
**What are the alternatives or competitors to this project?**
While there are no direct competitors, the alternative is unorganized gamer guilds acting inefficiently. Over the years, there may be a slow evolution of gamers figuring out what we've already learned, but we plan to accelerate this through our project

**How will this project get users? If your project is the type that faces a chicken-and-egg problem in the sense that it won't be attractive to users until it has a lot of users (e.g. a marketplace), how will you overcome that?**
The project includes an aggressive marketing campaign and a continual pull of new users through the Ember Sword social platforms and across other social media. This type of pull marketing is also designed to attract users to form new guilds on the Aragon platform

<br>

## Legal

**Will you be using an Aragon DAO for operating this project and receiving the funds? Yes/No**
Yes - our project requires a DAO to be created for Gamer Guilds and will be the central component of our project

**Are any of the project team members covered by non-competes or intellectual property agreements that overlap with your project? If so, please explain.**
No
<br>

## Aragon

**Why do you think Aragon is a good fit for this project?**
Aragon's core goal of enabling decentralized organizations is also the core component of the Finch West project, which is to enable gamer guilds as decentralized organizations. Given our thesis and vision (detailed in the attached proposal), we need a pre-existing platform that helps us build decentralized organizations, while we handle the other technical, organizational and marketing challenges of our project.

As blockchain gaming becomes one of the biggest applications of blockchain technology, Aragon should have a product ready in its portfolio to address this.

**Are there any existing Aragon projects that are similar or complementary to your project?**
We have not yet found Aragon projects that serve the same purpose. However, a number of Aragon apps are quite useful in moving our project forward (Payroll, Agent, Time Lock, Token Request, Memberships).

<br>

## Funding

**How much money are you requesting as a grant? (the maximum grant size we provide is $150k in USD value)**
Finch West is requesting $145,000 from the Aragon Grant

**Have you already received any grants or funds from 3rd parties? If yes, how much?**
No.

**Are you applying for funding to any other DAO platforms or grant programs? If so, that is not a problem as it increases the likelihood of your success, but it's important that we can take that into consideration if your project relies on multiple grants.**
No. 

**How do you plan to deploy grant funds? (split between research/development/marketing/etc)**
Please see our proposal (attached) for the outline of funding in further detail. 
- Labour: $30K
- Marketing Comms/PR: $10K
- Promotional artwork: $5K
- PIXEL Private Pre-sale: $35K
- LAND: $65K

**What is your expected monthly burn rate?**
Average burn rate is $4,833.33USD ($145K/30 months)
However, the burn rate for labor will be $1,000USD per month for 30 months

**Do you think this project will require additional funds once you have depleted the grant funds? If so, why? Where do you plan on acquiring further funding?**
We do not anticipate that the project will require funds once they have been depleted. This is because our project is designed with the intention of building assets and commercial interaction in the blockchain gaming industry. Specifically, we will be selling the assets and services on the Ember Sword game beginning Q1 2022.

<br>

## Roadmap

**How long do you plan on working on this project before shipping?**
We plan to develop the project between January 2020 until the game launch in Q1 2022.

**What are the key milestones you have to accomplish before you can ship a production ready product to users?**
Finch West project activities and milestones correspond with the Ember Sword game development timeline. The key milestones will be the following:
- PIXEL private pre-sale: Q2 2020
- LAND auction: Q4 2020
- Promotional artwork: Q2 2021
- Marketing Communications Campaign: Q4 2021

In addition, a number of smaller milestones and timelines have yet to be determined corresponding to game assets in development (i.e. world building and cosmetic development)

<br>

## Notes

**Is there anything else you would like to share or ask us?**
_**Please see the detailed project proposal (link above), which outlines our vision, as well as the market potential and project parameters**_
<br>
<hr>
<br>

Thank you for applying! A Nest team member will read and reply to this application within 72 hours. They will ask questions to better understand your project and then they will help you improve your application to maximize your success in the Nest program. If you have any questions as to what this looks like or next steps, please see our [Frequently Asked Questions](https://github.com/temp-nestdao/nest/blob/master/FAQ.md) page for more info.

Once again, thank you for applying to the Nest program. We look forward to working with you!

**Comment by pythonpete32** [comment]
Hi @ Thanks for Applying to Nest

Organisations within games are indeed an excellent usecase for Aragon DAOs. The economic activity within MMORPG games can really take off.

However, the Nest program generally focuses on teams developing Aragon infrastructure as opposed to direct usecase.

I do have some initial questions.

**On the Project**
> The Finch West project aims to build four guilds
- What exactly is a guild? 
- why four? Presumably they would compete for resources and talent (I don't knowmuch about gaming)

**On the Financials**
The $100k for PIXEL presale and land, this would be land and tokens you buy from Developers?

Is a $1k per month burn rate for two employees? You also mention 10 other roles, how will those employees be finance?

**On the size of the market**
*Is this the first game from the developers? 

*How many active users does the developers have in their other games?

*I had a quick look on like and found a discord server with 2500 people, what makes you confident the economic activity within the game will be enough to sustain your business?

**Comment by Finchwest** [comment]
Hi Aragon team, 

A great presentation was just posted to YouTube that illustrates the impact of blockchain gaming on decentralized organizations, so we wanted to recommend the Aragon team have a look: [https://youtu.be/2l9kVi9lTpk]

The video was posted yesterday, but was originally presented at Devcon 5 in Osaka Japan back in October. The presenter (Chris Robison) is part of a blockchain gaming startup (https://hoard.exchange) and we think he truly understands our thesis statement.

His arguments about decentralized organizations in gaming ("on-chain guilds") **starts at 13:00**, but we recommend watching the full video.

Have a great weekend
_- Finch West team_

**Comment by pythonpete32** [comment]
Unfortunately, we will not be moving forward with your proposal at this time. Nest is focused on infrastructure projects at the moment and we do not feel this proposal is the right fit. We hope you stick around in the Aragon community and build awesome stuff here.

All the best
