### ISSUE TITLE
AcuiQ

### ISSUE THREAD

**Issue by tutmoses** [aragon/nest#200]
# Nest Program Proposal Template

<br>

## About

**Project name:** AcuiQ

Project description: AcuiQ is decentralised acupuncture: a machine-learning webapp to parse symptoms into treatments, an OEM brand of press needles (‘Hot Spots’) to enable users to treat themselves at home safely and cheaply, and a crypto reward scheme / ownership model to incentivise user feedback to refine the ML model (funded by press needle sales).

Code repo and/or website URL (if any): https://AcuWiki.com/ (An early incarnation as a wiki that will be superceded by AcuiQ)

**Where did you hear about the Nest program and what prompted you to apply?**

Over the past few years I’ve set up a couple of companies and contracted several developers in pursuit of this vision. Quarterly reporting requirements for limited companies are painful in the UK and I have also had to take my last developer to court for non-performance. I won the case but, needless to say, limited liability is a significant obstacle to any resolution. Funding would enable me to restart development but for the last six months I have been soft-pedalling pursuit of VCs because of the prospect of having to set up yet another company to facilitate it. I heard about Aragon yesterday and sensed that this cuts the Gordian knot for me and is the only way to progress. I learned about the Nest program from watching the AraCon 2019 videos.

## Team

**Name of the project lead:** Andrew Ridge

**Email address of the project lead (whoever is filling out this application):** a.ridge@gmail.com

**List each other member that is/would be working on this project (LinkedIn/GitHub profiles are preferred but not required)**

Andrew Ridge (Founder): https://www.linkedin.com/in/apridge
Dr Enqin Zhang (TCM Advisor): https://www.linkedin.com/in/dr-enqin-zhang-consultant-chinese-medicine-1a1ab227/ 
Dr Gordon Hunter (ML Advisor): https://www.linkedin.com/in/gordon-hunter-b54b6916/ 

**What are the main roles of each team member?**

As above.

**Has the team already worked together? (please provide details)**

No, both Dr Zhang’s and Dr Hunter’s advice will only be required once the testing of the model begins.

**Is your team already present on the Aragon Forum? If Yes, what are your usernames?**

@libertant

## Progress

**How far along are you?**

‘Hot Spots’ - UK trademark										2018 / 03
AcuiQ.com purchased											2018 / 12
‘Hot Spots’ logo & packaging design								2019 / 01
‘Hot Spots’ packaging sample									2019 / 07
Clean data for 575 acupuncture points and ~14,000 case-studies /	2019 / 12
treatments ready to train the model.

**Is anyone using your product/application?**

Yes (AcuWiki.com)

**If yes, How many active users do you have and what kind of feedback have you received?**

AcuWiki.com has ~1300 users/month (Analytics data attached) but little active engagement because the relevant Wordpress modules are no longer maintained.

Here are some comments from users on LinkedIn about AcuWiki’s first incarnation, DIYacu.com:

"Wow Andrew - that's fantastic! really good maps - must have taken you ages. Will you make a book/publish on line?" - David

"Beautiful!! If there were a way to go from the close up on the point in skeleton view to close up in muscle and skin view, that would be very good. It seems like the only way to get the to the close up on those levels is to go from the wide view and zoom in. And if there is any way to get a higher resolution when you zoom all the way in, so the dots and numbers are crisp. And if there is any way to combine channels on one image, like Deadman does in the back of his book, so that you could see the relationship of the points. And make them printable. I just took the CA state boards and would have LOVED a tool like this. Nice work!!" - Debra

"Really good! Beautiful." - Martine

"I love that when you click on the small images of the individual points on the right, that the larger image scrolls up or down to that point. This is a cool feature and highlighting this would resolve some of the comments Debra is making. One could look at the small image on the right with the muscular view and then see the dermal or skeletal images on the left." - Leslie

"Are you an acupuncturist or a graphic designer? It looks great!!! 
Thank you for sharing it with us." - Betty

" This is absolutely fantastic. 
Do you have the rest of the channels ready? 
Thanks so much." - Zinnia

"I agree with everyone--fantastic, great! An app would be a great tool to have." - Denise

"Its really nice, one, are u planning to make an app for a phone as well?" - Nilesh

"It is pretty helpful+ Would be nice if there is a Iphone or Android app for it too... :)" - Wendy

"Andrew, it's fantastic! Is there a possibility to download the maps? I didn't find it. And if you will create an app, will it be for android also?" - Ina

"Very nice...many congratulations. How about a cross-sectional view that shows veins/arteries/nerves/lymph etc. - now that would make this product stand out from the crowd!" - Robin

If you've applied previously with the same idea, how much progress have you made since the last time you applied? What has changed?

n/a

<br>

## Idea Problem

**Why did you pick this idea to work on? Do you have domain expertise in this area?**

My expertise and motivation are as a consumer: in 2010 I visited Japan where my father-in-law was using press needles for a baseball injury. Back in the UK I discovered that acupuncture sites were generally woefully presented, deliberately gnostic, lacked unanimity, and were openly hostile to self-treatment. My thesis was that acupuncture must be algorithmic and could thus be distilled into some kind of wiki. As a creative, I thought at the very least I could make something prettier so I built DIYacu.com (now defunct). That experience plus user feedback hardened my conviction that the industry is hidden behind a fortress of protectionism that will not acknowledge that if users have the tools and information, they can treat themselves acceptably well; for me, it is territory to be conquered.

**What's new about what you're making? What do people resort to because it doesn't exist yet (or they don't know about it)?**

AcuiQ does not pay any deference to acupuncture practitioners: it assumes that treatment protocols can be learned by ML models and that needle insertion, being typically shallow, can be replicated with self-applied press needles. Indeed, practitioners will often prescribe press needles to patients for supplementary self-treatment, which is a tacit admission that their value-add is protocol knowledge rather than actual needle application.

AcuiQ is also agnostic on the efficacy and/or placebo effects of acupuncture. It assumes only that the market price of treatment reflects real utility and seeks to deliver that utility in a more efficient way.

The ML model will take published cases at face value and will eventually be able to identify outlier results, creating a de-facto model of industry best practice. This may serve as a benchmark and eventual governing authority for the industry.

In the absence of a self-treatment solution, patients will either pay $60/hr for ~6 sessions with an acupuncturist or if they are determined to treat themselves will buy press needles and follow the instructions on a forum or website. AcuiQ facilitates and supercharges this latter option.

**Have you talked to people about what you're making? Do people want it and do you have examples of this?**

AcuWiki.com is the best evidence I have that thousands of people worldwide are searching for self-treatment solutions. I have anecdotal evidence myself, online and from friends and family that press needles work.

<br>

## Market

**What is the target market or end user in mind for this project?**

Self-acupuncture has the potential to be marketed worldwide to all strata of society. In the developing world such as China and India, acupuncture is well accepted but could benefit from a dominant brand. In the developed world, the zeitgeist is to reduce healthcare costs and treat oneself more holistically, which favours the disintermediation of practitioners.

The strategy would be similar to how Uber opened up the taxi market to a huge, previously unserved demographic. Just as taxis can now replace car ownership, so lowering the barriers to self-acupuncture can make it as common as aspirin.

**What are the alternatives or competitors to this project?**

Current alternatives are the myriad high-street TCM shops that serve roughly 5-50 patients per day. They epitomise the practitioner-patient model and compete for business on platforms such as Treatwell.

Online, there are sites such as YinYangHouse.com, Acupuncture.com and Acufinder.com. They host a wealth of information and the forums are well populated, but their purpose is to drive patient referrals so they are not aggressively expansionist.

One could imagine a paraphernalia company such as Seirin adding a diagnosis service but it would be difficult to do without alienating their existing customer base of practitioners.

A company like Acugraph would have the data to compete but would be unlikely to effectively opensource that data in pursuit of sales and risk alienating their practitioner clients.

Finally, a data startup, possibly from China, would be the most likely future competitor. At $210bn by 2026 (https://www.grandviewresearch.com/press-release/global-alternative-complementary-medicine-therapies-market) the market is big enough to support many companies, but it would be a race to establish a dominant brand.

How will this project get users? If your project is the type that faces a chicken-and-egg problem in the sense that it won't be attractive to users until it has a lot of users (e.g. a marketplace), how will you overcome that?

AcuiQ does not depend on a marketplace or community, but a frictionless UX, low-cost products and the ability to share treatments would create essential virality. Initially, I would leverage existing users of AcuWiki.com to drive traffic. The webapp would not require registration or any personally identifying data but would store treatments locally as SHA256 web addresses. This ensures the site would be as frictionless as possible.

<br>

## Legal

**Will you be using an Aragon DAO for operating this project and receiving the funds? Yes/No**

Yes.

**Are any of the project team members covered by non-competes or intellectual property agreements that overlap with your project? If so, please explain.**

No.

<br>

## Aragon

**Why do you think Aragon is a good fit for this project?**

Aragon seems to be perfectly suited for AcuiQ. To compete long-term, AcuiQ must be community-owned to align user incentives with feedback to the ML model. Traditional company structures would introduce unacceptable levels of friction to the administration of such an arrangement. In addition, crypto offers the prospect of frequent - even daily - dividend payments to motivate previously unobtainable levels of customer engagement.

**Are there any existing Aragon projects that are similar or complementary to your project?**

Not that I know of.

<br>

## Funding

**How much money are you requesting as a grant? (the maximum grant size we provide is $150k in USD value)**

$150,000

**Have you already received any grants or funds from 3rd parties? If yes, how much?**

£32,453 ($41,610) developer funding from Raj Dhonota (https://rajdhonota.com/) in 2015 for AcuWiki.

**Are you applying for funding to any other DAO platforms or grant programs? If so, that is not a problem as it increases the likelihood of your success, but it's important that we can take that into consideration if your project relies on multiple grants.**

No.

**How do you plan to deploy grant funds? (split between research/development/marketing/etc)**

Initial development - webapp, model & store (3 months)				£27,000	($34,500)
Hot Spots press needles (5000 units)							£  5,650	($  7,225)
Dr Zhang - data gathering: acupoints & herbs (3 months)			£18,000	($23,000)
Dr Hunter - ML audit											£  2,000	($  2,550)

Ongoing development - model, Aragon, crypto, ipfs, bugs, etc.		£27,000	($34,500)
Store products - herbs, teas, etc.								£  5,000	($  6,400)

Salary - research, management, marketing, etc.					£32,350	($41,375)

TOTAL (12 months)											£117,000	($149,550)

**What is your expected monthly burn rate?**

Average ~£9750 ($12,470) 

**Do you think this project will require additional funds once you have depleted the grant funds? If so, why? Where do you plan on acquiring further funding?**

An outlay of ~£10,000 on store products should yield ~£100,000 ($128,000) in sales, which will all be ploughed back into the business with a focus on self-sustaining profits. That said, a further cash injection for a large-scale marketing effort would help to steepen the curve. My preference would be an equity partner at that stage.

<br>

## Roadmap

**How long do you plan on working on this project before shipping?**

Three months with the right developer.

**What are the key milestones you have to accomplish before you can ship a production ready product to users?**

Train the ML model and house it in a well-designed webapp with integrated store.
Order 5000 OEM boxes of ‘Hot Spots’ from wholesale supplier.

<br>

## Notes

**Is there anything else you would like to share or ask us?**

1. I have struggled to find an available VueJS / Tensorflow / PostgreSQL developer. Would you have anyone in your network who fits the bill?
2. Pitchdeck & AcuWiki analytics data attached.

<br>
<hr>
<br>

Thank you for applying! A Nest team member will read and reply to this application within 72 hours. They will ask questions to better understand your project and then they will help you improve your application to maximize your success in the Nest program. If you have any questions as to what this looks like or next steps, please see our [Frequently Asked Questions](https://github.com/temp-nestdao/nest/blob/master/FAQ.md) page for more info.

Once again, thank you for applying to the Nest program. We look forward to working with you!

[Analytics All Web Site Data Audience Overview 20160801-20200228.pdf](https://github.com/aragon/nest/files/4272574/Analytics.All.Web.Site.Data.Audience.Overview.20160801-20200228.pdf)
[AcuiQ pitchdeck.pdf](https://github.com/aragon/nest/files/4272578/AcuiQ.pitchdeck.pdf)

**Comment by burrrata** [comment]
This is not related to a Nest RFP and it's not directly related to Aragon.
