### ISSUE TITLE
Aragon Nest Proposal: Courses for beginning cryptocurrency investors/traders/users

### ISSUE THREAD

**Issue by dylandamsma** [aragon/nest#4]
# Aragon Nest Proposal: Courses for crypto beginners & crypto entrepreneurs

## Abstract
It’s evident that cryptocurrencies have steadily risen in popularity over the past year. Many retail investors have gotten into this space and it wouldn’t surprise us if even your grandparents have asked what this bitcoin thing is all about. After all, interest rates on savings accounts are at an all-time low and who doesn’t want to benefit a bit from the crypto-run.

Obviously, we support the growth of this industry, but we also recognize all its pitfalls. It’s a wild west out there with Ponzi schemes, fraudulent coins & wallets, phishing attacks, vaporware projects, security issues and besides all of that, let’s be honest… cryptocurrencies are not a particularly friendly investment vehicle for people that are not tech savvy.

It’s our duty to protect newcomers into this industry through educating them properly, while there will always be people that are not willing to put in the time, we’ve seen over and over again that there’s many that do want to learn more, but simply can’t find good educative sources to do so. The high-quality courses that are out there are usually aimed at the technical aspects of blockchain technology and those that have a financial perspective are usually biased in their advise or charge ridiculous fees for low-quality webcam videos. 

In the course the topics addressed can be such as:

1. The basics of cryptocurrencies and making them understandable for beginners
3. Help people figure out how to purchase, transact & safely store cryptocurrencies.
4. Protect users from common mistakes & scams.
5. Helping beginners understand the differences between various currencies.
6. Answer the most commonly asked questions by beginners such as "should I invest in cryptocurrencies?"

The goal is to rope in multiple perspectives on the industry and give people a broad understanding of the market, cryptocurrencies as an investment vehicle and educate people on common sense personal finance basics.

Producing a high-quality course obviously goes paired with costs as it requires proper copywriting & editing to make the information easily understood, good design, high-quality videos and additional costs to travel to meet & interview experts on the topics of crypto and personal finance.

## Deliverables
1. A high-quality, but free to consume, beginners course addressing all the important topics and questions beginners may have.
2. A place where beginners can go to get further help in case necessary
3. A course on utilizing Aragon as an entrepreneur to build self-governing communities or run a distributed business.
4. Events to reach & educate beginners and promote the course.
5. A place for people to learn about the different fundamental values of cryptocurrencies and can find easily accessible factual data about the various cryptocurrencies out there.

## Grant size
Funding: Up to $75k in ETH to cover development, course creation & promotion costs.
Success reward: Up to $50k in ANT, given out when all deliverables are ready.

## Application requirements
- Details of the team members, alongside with their willingness in terms of implication
- Estimated average burn rate for completing the deliverables
- Legal structure to be adopted, if any

## Development timeline (roadmap)

The first course should be up on Q1 2018, and all other remaining modules should be delivered by Q3 2018.

**Comment by DaniellMesquita** [comment]
@dylandamsma
This course can be added to an education platform: https://github.com/aragon/nest/issues/123
