### ISSUE TITLE
Giveth DApp Completion facilitating Aragon DAC Proposal

### ISSUE THREAD

**Issue by parkwil89** [aragon/nest#43]
# Aragon Nest Proposal: Giveth DApp Completion facilitating Aragon DAC

## Abstract
Giveth is re-engineering the non-profit funding system, by creating an entirely free, open-source DApp on the Ethereum and Rinkeby Blockchains. Our DApp utilizes LiquidPledging and a series of DACs, campaigns and milestones (described in product definition) to automate away bureaucracy and enable Change Makers (nonprofits, community based organizations, faith-based organizations, social services agencies, etc.) to operate with a high level of transparency and accountability. The DApp’s LiquidPledging smart contract system provides Givers the power to veto fund allocations and even withdraw funds at any point until the moment they are locked in and dedicated to a specific cause. This functionality forms the foundation of the DApp and creates a better world for parties on both sides of a transaction, the Change Makers and those that give to them.

Giveth has been developing our DApp since October 2016 and in May of 2017 the LiquidPledging design was created to better fulfill the systems needs. In late January this year we decided to restructure it as an AragonApp to provide added desired functionality (specifically, convenient access control schemes and upgradability). The goal moving forward is to finish building the DApp, creating an open source environment that will add additional levels of accountability, transparency, decentralized governance and community for users without requiring traditional legal structures. 

In recent conversations with the Aragon team we’ve discussed using the DApp to grow the Aragon ecosystem by developing an Aragon DAC. The goal of this DAC would be to decentralize Aragon Development and build the Aragon Community.

The DApp is nearly usable by non-Giveth groups, we are testing the bridge on Ropsten and Rinkeby right now. The Aragon DAC would be one of the first DACs on the platform. The Aragon DAC would utilize LiquidPledging to fund and govern the decentralized development of the Aragon platform. As the DApp evolves and adds greater functionality the Aragon DAC will be able to have its issues addressed and continue to evolve itself.

We propose to finish the DApp and make the Aragon DAC a reality.

## Deliverables and timeline

1. Integrate AragaonAPP version of LiquidPledging into current Giveth
DApp - July 2018
2. Finish testing the bridge to Rinkeby - July 2018 
3. Finish testing the DApp until it is safe and easy to use - September 2018
4. Create Aragon DAC - September 2018
5. Migrate current Giveth DApp UI to Aragon - start in September 2018 

## Grant size

Funding for reimbursement: 26.99610065 ETH
Funding for future work: $154,500 

## Application requirements

- DApp created and in alpha testing 
- Developed LiquidPledging smart contracts 
- Full product definition available 
- Video explanation and roadmap 
- Team bio’s and governance details

**Comment by mariapao** [comment]
Hi @parkwil89 thanks for submitting your proposal. Aragon needs this application so this proposal is approved. The next step is to submit the request for funding taking into account the application requirements agreed in this proposal. Make sure you follow [these ](https://github.com/aragon/nest/blob/master/README.md)instructions )(point #3)

I only have one small question: what exactly funding for reimbursement means? money that you have spent in the development of the DApp already? We can discuss this point further during the next phase of the application process.

Feel free to ask any questions you may have about the process.

**Comment by parkwil89** [comment]
Hi @mariapao thank you for taking the time to review the application and we are very pleased to hear it's approved! 

Yes, the reimbursement is for time spent working on this already, namely creating the AragaonAPP version of liquidpledging. Of course I'll wait for any specific questions on the funding request and will be sure to provide a detailed response.

Thanks again and you should see a pull request from me soon!

**Comment by luisivan** [comment]
I just want to chime in to point out that we should be consistent about reimbursements, and since we haven't done any of those, I think we should consider if it makes sense or not. Everything else is looking good!

**Comment by mariapao** [comment]
I'm closing this proposal as it is no longer relevant to the Aragon project
