### ISSUE TITLE
Horizon NGO - United Basic Income platform

### ISSUE THREAD

**Issue by heinrichshorst** [aragon/nest#46]
## Horizon NGO
**The first decentralized platform for uniting universal basic income initiatives!**

Through the so-called "Horizon Factory", organizations are able to create their own independent basic income service, for their target audience only. This service is an instance of the global Horizon basic income service (so with the same functionalities), but it is completely controlled by the organization itself. To fuel Horizon's main financial reserve, needed to pay out its own token holders, each organization pays a small fee for creating a new instance and contributes a wee percentage for each deposit to its own basic income service. The benefits for all are clear. Organizations only need to invest a fraction of what it would normally cost to build an automated basic income service and, by combining the efforts of like-minded initiatives, Horizon NGO is able to build a larger financial reserve for its token holders. The higher the reserve, the more people who can build a basic income for themselves.

To step into Horizon's public basic income service, one or more Horizon tokens can be acquired. A one-time fee per token guarantees an infinite and immutable benefit. Regular payouts to all token holders are made possible by the financial reserve, additionally fueled by donations and partnerships both inside and outside the crypto world. Needless to say that one of Horizon's major tasks is to keep increasing the reserve, so that more tokens can be released and more people can gain higher payout amounts. On a side note, it might be interesting to know that no Horizon tokens will be directly distributed to Horizon team members. They will also have to acquire tokens through the public channels.

In the end, this project is all about trying to create an opportunity for a large group of people to find a way to a more meaningful life. Every bit of financial support could help lead the way to new insights, less worries and hopefully more smiles and happiness.

##  Q&A

**Can you explain what UBI is, specifically the "Universal" part? Does it mean all people on the planet, or something else?**

In theory, a universal basic income means a basic income for everyone on the planet. Needless to say that, in practice, this will be extremely hard, if not impossible, to implement. Nevertheless, a rapidly growing number of people, including politicians and well-known entrepreneurs, are supporting the idea. A few pilot projects have already been organized on a relatively small scale and I'm sure that, currently, many more are in the pipeline. According to Ray Kurzweil, an American author, computer scientist, inventor and futurist, "a universal basic income will be common throughout the developed world by the early 2030’s and globally by the end of the same decade". To me, this feels quite optimistic, but when we all join forces this might actually be possible. Joining forces is everything what Horizon.ngo is all about! We have developed a platform through which organizations can set up an independent basic income project, supporting their own community while contributing to Horizon's global basic income service. Therefore, we decided to talk about a United Basic Income. Uniting basic income initiatives world-wide could be key to creating a universal basic income for the entire planet.

**What is the history of UBI? Where have such policies or models been attempted and what are the results?**

In summary, the concept of a universal basic income is still a hot topic, heavily discussed in many circles. When we look at Wikipedia, for example, we can see a list of quite a few experiments from the past. Most recent examples include pilot projects in Finland, Scotland and The Netherlands. To some degree, I'm sure that they have been successful, but the challenge is to extend such a program over a longer time, for a larger group of people. In other words, we're not quite there yet. Personally, for Horizon's basic income strategies, I was inspired by the Eastern Band of Cherokee Indians. This Native American tribe shares profits from tourism and, more importantly, from its casinos with their community, as a kind of basic income. Perhaps not the most ethical example, but it pointed me towards the idea that basically every company, institute and organization can contribute to a United Basic Income. We shouldn't only rely on governments to fuel the finance reserve necessary for paying out basic incomes. Strategic partnerships with other parties can be made. And this doesn't mean simply asking for donations. Not at all. Rewarding projects can be set up to the benefit of every party involved. In our white paper, we mention such a case study. It is still work in progress, but negotiations are rapidly moving forward in a positive direction. As we are still in a startup phase, it's hard to predict where we will be in a few years from now, but it looks promising at least.

**What is Horizon and how are you different from the other UBI tokens out there?**

Next to our approach of uniting basic income initiatives and forging strategic partnerships world-wide, Horizon.ngo differs from other decentralized UBI initiatives in two ways. First of all, we decided to pay out basic incomes in Ether, a coin that already has an established value (1 ETH ≈ $500 on April 16, 2018). This means that we do not have to spend any time, money and effort in marketing yet another cryptocurrency, one of our own design, which doesn't have any value to begin with. We can fully concentrate on striking deals that fuel Horizon's basic income reserve. Second, because our smart contracts are developed for Ethereum, we immediately benefit from the huge community behind this blockchain platform. The software is continuously updated and supported by countless experts. This, again, allows us to focus on our core business, creating a United Basic Income platform by joining forces, forging partnerships and positively influencing the lives of many. Important to remember is that the Horizon platform is the only system out there that offers a factory for setting up independent basic income services, using already existing tokens or tokens created through the Horizon smart contracts. Interesting to know is also that nobody in the Horizon team is getting any basic income tokens by default. We all have to acquire them through the same public channels as everyone else. So quite a few differences with other UBI projects, although we all target the same objective. Horizon.ngo allows bundling all these efforts and therefore offers the most interesting options for any organization, to start experimenting with the universal basic income concept.

## Deliverables

1. A set of ERC20 compatible smart contracts implementing the Horizon Factory and Splitter services.
2. A fully functional DApp, integrated in our WP website, built using Ethereum's web3 API.
3. A DAO for managing Horizon's entire United Basic Income service.

## Grant size

Funding: 

$10k/month in ETH, for the next 10 months, allowing continuous development, testing and new feature implementations (like an ERC721 compatible version of the Horizon Splitter), as well as maximizing international promotion efforts (e.g. the next BIEN congress in Tampere, Finland) and investing time in forging new strategic partnerships.

Success reward: 

Early bird strategic partnership with benefits for all parties involved. Options are open for discussion, of course.

## Application requirements

White Paper: http://horizon.ngo/wp-content/uploads/2018/06/whitepaper.pdf

Core team: 

**Dirk von Heinrichshorst** is an engineer in electronics and telecom, but has been working in IT his entire career. He spent many years developing his web development skills before starting his own company in Belgium, serving top clients and building innovative prototype applications. After 6 years of leading this company, he switched his focus to business development and started working as a consultant before moving to Germany. By then, he was introduced to blockchain technologies, which seriously caught his attention.

From an early age on, **Eliott Teissonniere** has been interested in computer science. His passion for cybersecurity, for which he analyzed advanced threats and built cutting edge tools, led him towards blockchain and smart contract development at a time when hardly anybody had heard about Bitcoin. Relatively quickly, he became the CTO of Bitnation, "the world's first Decentralized Borderless Voluntary Nation". For Bitnation, Eliott designed complex frameworks to support a reputation system as well as a DAO. As a co-author of Bitnation’s white paper, he detailed the inner workings of the systems he developed. After leaving the Bitnation team, Eliott started to work as a blockchain consultant, helping companies transition to this new technology. He also released the world's first DApp for couples to get married on the Ethereum blockchain. Strongly focused on artificial intelligence, trustless systems, mesh networks, cryptography and security, Eliott is helping to pave the way for the upcoming digital revolution.

Available funds will be used to compensate core team members time, efforts and expenses.

Horizon NGO (http://horizon.ngo) is a non-governmental organization listed by OnGood, an organization that manages all .ngo domains.

## Development timeline

Q2 2018: Testnet live
Q3 2018: Mainnet live
Q4 2018: Horizon DAO
Q2 2019: Mobile app

**Comment by heinrichshorst** [comment]
I would like to mention that, obviously, we are also considering Aragon for Horizon's DAO, but we have to check whether or not it will be entirely compatible with our system. Development paths could be aligned in some way of course. Happy to discuss the possibilities.

**Comment by mariapao** [comment]
Hi @heinrichshorst thank you very much for submitting your proposal!

Universal basic income is an interesting topic. This is an idea that is worth experimenting with and we are following the development of the different projects that are working and doing research on UBI. However, this project is not a fit for nest. We are currently focusing on funding the development of basic infrastructure or dev tooling for Aragon and Ethereum. Therefore, we have decided to reject this proposal. 

We appreciate your participation very much and If in the future you are working on something that is a fit for the program, do not hesitate to apply again!

**Comment by heinrichshorst** [comment]
Hi @mariapao, do you know of other programs where we could apply for some funding?

And perhaps, as a token of your support, we can convince you in a one-time donation to Horizon's financial reserve, used for paying out our token holders? :-) http://horizon.ngo/donations/

**Comment by mariapao** [comment]
Hi @heinrichshorst I know there is the EF grant program and also the ECF grant program. But I don't  know a lot of details on the requirements of those programs. For the moment we don't participate in donation programs. The foundation can use the funds only for the development of the project.
