### ISSUE TITLE
Aragon Nest Proposal: Dapplication - A Smart Contract Application For Digital Legal Personality In The EU

### ISSUE THREAD

**Issue by jtiannelli** [aragon/nest#65]
Aragon Nest Proposal:

**DAPPLICATION: A SMART CONTRACT APPLICATION FOR DIGITAL LEGAL PERSONALITY IN THE EU**

per #48

_Abstract_
The current environment finds most non-incorporated blockchains unable to utilize traditional financial or legal institutions or to enter litigation to defend itself if necessary.  Nearly finalized legislation in Malta an open-border EU member state will soon allow DAOs and other innovative technologies to achieve their own legal personality without incorporating.  This digital legal persona and its right to exist and conduct business should then be applicable for participation by residents of other EU member states as is the case with other cross border companies, foundations, and persons.

_Concept_
A free and open-source and permission-less ethereum based smart contract providing simple DAOs with a logical step by step chain of prompts and requests for information relevant and necessary to submit an application to achieve this new legal personality, right to exist, and even defend itself in litigation if necessary. This dapp will both store a digital record of the Innovative Technology Application's purpose team etc. as required by the laws and allow the user to print a submit-able application to the Malta Digital Innovation Authority, the only jurisdictional authority in the EU currently accepting these types of applications to be a non-incorporated non-foundation, digital code-based legal entity. This does not involve setting up a foundation does not require significant capital to apply. 

***This template will also include registration requirements for DAOs that are not simply governance models but are issuing ICOs, seeking profits, or otherwise dealing in financial assets, however these organizations will need to employ lawyers, registered agents, and auditors in addition on their own accord and at their own expense to be compliant with the proposed regulations***

_Deliverables_
1. Prompt Template
Series of 100+ detailed questions grouped into relevant categories (not all information is applicable to all interested applicants) which when answered constitutes a full application to the relevant authority to gain this new digital legal persona
2. Legal Review
Professional legal review and audit by Maltese law firm confirming the steps are an accurate and adequate template to gaining this new legal personality
3. Develop and Test
Develop series of prompts into a dapp and deploy on testnet for verification of functionality
4. Deploy
Deploy dapp on mainnet, make available for free and open-source future development

Grant size
Deliverable 1. - 12.5k in ETH
Deliverable 2. - 25k in ETH
Deliverable 3. - 12.5k in ETH
Deliverable 4. - 25k in ETH
Success Reward - 50k in ANT

Application requirements

This project will be deployed by the TechCollect team.  Our in house legal efforts have led us to the capability to create this list and our in house tech is capable of turning it into this contract.  Turn-around should be fast and efficient, our team is outlined below as well as additional information on Ganado Advocates the law firm we will be using to conduct the legal review. Team bio's are as follows:

Joseph (JT) Iannelli
Successful Entrepreneur and small business enterprise expert.  Experienced manager and team leader. Challenger of the status quo. Fan of decentralization. Visionary and thought leader, founder of TECO Token and Foundation Concept.
 https://www.linkedin.com/in/joeiannelli/
https://twitter.com/joe_iannelli
https://www.facebook.com/jt.iannelli
https://github.com/jtiannelli
 
Stephen Reed
https://www.linkedin.com/in/stephen-reed-pgh/
Stephen brings nearly a decade of Product/Project Management experience to the TECO Foundation, having spent his early professional career starting two companies, and learning how to effectively manage rockstar teams from world class organizations. He was initially introduced to Cryptocurrency in 2014 and quickly became an early evangelist and token purchaser in Ethereum.

Muhammad Azam
https://www.linkedin.com/in/muhammad-a-36425825/
Management Accountant – (CIMA)
Master of Business Administration 
Bachelors of Commerce
Certifications:
CFA Institute Investment Foundation
IBM Blockchain Essentials
Having an extensive experience of more than 10 years in the field of finance, financial ,capital markets, and more specifically Mutual Fund Industry, working on variety of areas such as Business strategy, Regulatory compliance, Operations management, Accounting, Risk management, Project management, and business advisory, he brings with him the flare of problem solving, strategy setting, increasing efficiency in business protocols.
 
Tom Whitbread
https://us.linkedin.com/in/tomwhitbread
Certified Linux System Administrator by the Linux Foundation. Decentralized App Developer (Ethereum, Neo, EOS, Aragon), Private Trader, Author Fullstack Isomorphic Multiplatform Apps, Fintech dapps and traditional web app developer with a strong background in Linux and especially high performance tuning. Having worked in I.T for over a decade - Tom has experience operating in tech companies through several waves of economic disruption, from low bandwidth dial-up to high definition streaming content.

GANADO Advocates 
a leading full-service business law firm based in Malta. We provide legal services to global and local.
www.ganadoadvocates.com/

_Development timeline_
The development timeline will be the following one in regards to each deliverable:
1. August 15th 2018
2. August 31st 2018
3. September 15th 2018
4. September 30th 2018

**Comment by tomtom87** [comment]
Hi, Tom here (CTO of Tech Collect) this was our reasoning for what the community needs for DAOs to be legally recognised and operating in the EU specifically (and other crypto-friendly jurisdictions), open to hear any feedback on improvement and critiques... Cheers!

**Comment by jtiannelli** [comment]
Happy to work with Aragon and Giveth and our new mentor @vojtechsimetka via the Blockternship program. If grant funding/awards become part of the blockternship program (I think there is a potential for 4, 6, or 10 Ether) we will remove those expenses from our deliverables here, as we still wish to pursue this via Nest (@sohkai) as we are planning on being an Aragon based organization. P.S. Nice to see you on our Blockternship assignees @Smokyish

**Comment by mariapao** [comment]
@jtiannelli thank you for submitting your proposal. We really appreciate the time, effort and desire to collaborate with the Aragon project. 

If I understand correctly, this proposal is more about automating the process of registering a "DAO" with the Malta jurisdiction. If this is the case, I don't understand why do you need a blockchain for this? 

To be honest, and taking into that I'm not an expert in Malta's law and I haven't been able to review in detail Malta's regulatory framework for blockchain tech, specially the "Innovative Technological Arrangement and Services Act", I think that if a DAO would follow the requirements of this new law it would not be a DAO anymore. One of the requirements is to have a legal representative, for example. IMHO, DAOs don't need legal personality and the minute you give these new organizations legal personality you instantly are converting these organizations into some other legal entity that follows the requirements of a specific jurisdiction. 

We would be more interested in having a template to incorporate a company on Aragon according to the Malta law and through those legal entities DAOs could interact with the Malta jurisdiction, for example. I don't know if this is even possible according to Malta's law. 

For all the above, we decided not to approve this proposal.

**Comment by jtiannelli** [comment]
I think we are quickly learning that there is just an un-bridgeable gap between the actual laws and our ability to explain them to people who aren’t familiar with legislative review. 

This legislation is in fact the furthest along method to register a DAO without a legal representative in the world.  Because it is in the EU member state this can then be used to authorize interactions within the entire EU. 

As with most types of organizations there are different regulations here which apply for different types, and the most lenient regulations apply to DAOs that are not set up as profit-seeking initiatives.  

This would be like looking up the rules in a tough jurisdiction for setting up an S-Corp., and then deciding not to sell your artwork on Etsy because you thought you had to comply with all of them.  Or even worse deciding not to start a charity.

 To anyone who can understand these concepts or has a need, they can be followed along on our Github as we continue developing this solution
https://github.com/reed0023/technologycollection?files=1

 I also feel like I’ve been around here long enough to admit that I feel a little offended such interest is being given to a “long-shot”, expensive, year away lobbying proposal in Delaware which would require corporatized aspects in some fashion to be allowed engage in the US only... and no interest has been given to this in the EU which doesn’t require the corporatization, is much further along, costs a 1/3 of the budget and helps residents of dozens of nations.
