### ISSUE TITLE
GlobalwarmingDetectionApp

### ISSUE THREAD

**Issue by mangodevelopments** [aragon/nest#68]
_See the [Guide for submitting a proposal for grants](https://wiki.aragon.one/nest/guides/guide_for_submitting_a_proposal_for_grants/) for further details on submitting a grant proposal_

# Aragon Nest Proposal: climate change
## Abstract
climate change is a issue that we must work together to solve to protect our beautiful planet from harmful gasses. The scientists believe if we don't act now there could be damage that could change the planet we live on.  Multiple lines of scientific evidence show that the climate system is warming. Many of the observed changes since the 1950s are unprecedented in the instrumental temperature record, which extends back to the mid-19th century, and in paleoclimate proxy records of climate change over thousands of years. The phenomenon is sometimes called "anthropogenic global warming" or "anthropogenic climate change" in view of the dominant role of human activity as its cause. we must do our best to protect our nature for future generation.  an app Allows scientists and general public to report weather changed around the world so we can use data to make changes to help keep our world healthy and bulletproof for the future generation.

generate a smart system app that will have dashboards for different scientist to share there discoveries and extreme weather events to monitor the weather and glasses around the world to find trends and solve weather issues and reduce unhealthy gasses in the atmosphere.
## Deliverables

1)A toolkit built on top of aragonOS that enables a team, scientists, agronomist specializes in soil and crops. An astronomer studies stars, planets and galaxies. A botanist specializes in plants. A cytologist specializes in the study of cells. An epidemiologist studies the spread of diseases. general public and weather scientists to work together and share information and data, to allow us reduce the negative  impact we are having on the planet

2) app to monitor and analysis data on the planet and dashboards that represent the data in understandable and useable format. data can help farmers and other industry planet around weather predictions
3) web based platform for reporting and data analysis 
.
Grant size 
Funding:
 150k Euro in ETH, split into chunks paid out over achieved deliverables.
Success reward:
50k Euro in ANT, given out when the final public release is ready.

Details of the team members, alongside with their willingness in terms of implication
- Estimated average burn rate for completing the deliverables
- Legal structure to be adopted, if any

project manager -vision, data scientists  

Wahid hamid - full time 

Adam ali - full stack engineer- part time  

Grant ollson - software engineer - part time 

James smith -lead developer -part time 

doctor Malcom Ruther global weather expert-part time 

## Development timeline

The development timeline will be the following one in regards to each deliverable:

1.September  2018
-project plan 
-project management 
- design of  prototype app 
-team allocation 
2. November  2018
- development of design 
-prototype
- testing and implementations
-demo and test  

3. December 2018 
- testing and beta version 
- marketing of beta version 
- feedback and changes if required on beta

4. January 2019 
- product launch

**Comment by mariapao** [comment]
Hi @mangodevelopments thanks for submitting your proposal. 

Climate change is a problem we need to solve or reduce as soon as possible. The global warming detection app is a very interesting app to help tackle the problem. However, this app is not a fit for the Nest program at this stage. Currently, we are focused on funding basic dev tooling and infrastructure for Aragon and/or Ethereum. Thus, this proposal is not a candidate for funding this time. If in the future you are working on something that is a fit for the program, please apply again. We appreciate your participation very much!
