### ISSUE TITLE
PHD reserach:Tooling that improves developer experience:

### ISSUE THREAD

**Issue by teamNapier** [aragon/nest#94]
# Aragon Nest Proposal: PHD reserach:Tooling that improves developer experience:

## Abstract
Field that the eth/argon community is eager to research and explore to expand the ecosystem..
developers need to make the ecosystem more robust and user-friendly for existing and new users. 
AIMS
aim is to answer 5 key question and  submit and proposal for the developer community, so they can develop tools that the market condition requires to further the development of the ecosystem of smart contracts and argon nest and eth.
1) to identify what the ecosystem requires to make the it more widely adopted within  the global economy. 
2) identify the key tools required to improve developer tools, 
3) what makes the current most used tools success? identify advantages and disadvantages of these tools.  survey the ecosystem
4) what sector of tools and developers are using the new ecosystem tools and are they huge improvements from previous products within the marketplace.
5) does productivity and education impact the speed of new tools introduced to the marketplace? can there be more improvement on creating tools that meet the demand and future of the industry, can code be more robust and adaptable.

## Deliverables

1.PHd Research proposal 
2. background reading 
3.Research questions 
4. methodology 
5. developer proposal 
6. release finding to academic community 

## Grant size

Funding: Up to $25k in ETH, Success reward: Up to $50k in ANT, given out when all deliverables are ready.

## Application requirements

Aim is to answer 5 key question and  submit and proposal for the developer community, so they can develop tools that the market condition requires to further the development of the ecosystem of smart contracts and argon nest and eth.
1) to identify what the ecosystem requires to make the it more widely adopted within  the global economy. 
2) identify the key tools required to improve developer tools, 
3) what makes the current most used tools success? identify advantages and disadvantages of these tools.  survey the ecosystem
4) what sector of tools and developers are using the new ecosystem tools and are they huge improvements from previous products within the marketplace.
5) does productivity and education impact the speed of new tools introduced to the marketplace? can there be more improvement on creating tools that meet the demand and future of the industry, can code be more robust and adaptable.

## Development timeline

The development timeline will be the following one in regards to each deliverable:

1. September  2018- PHd Research proposal 
2. October  2018- background reading 
3. November  2018- Research questions  identification
4. December 2018- main research and developer research 
5. February 2019- developer proposal 
6. April 2019 -  release finding to academic community 

Team 
main researcher student - mr hamid 
access to full computing/ research  department for advice and help, Napier has a blockchain lab with specialists in the field. of crypto and eth.

**Comment by mariapao** [comment]
Hi @teamNapier thank you for submitting your proposal. 

We have reviewed your proposal and it is not a fit for the program. Nest doesn't focus only on research work. Research is important but right now we need teams building dev tooling and infrastructure. Also, we just funded a team that is going to be working on research about specific UX needs of distributed applications and design challenges. We are not interested on more research about these topics at the moment. 

For all the above reasons, we have decided not to approve this proposal. If in the future you are working on something that is a fit for the program, please don0t hesitate to apply again. Thank you!
