### ISSUE TITLE
Bridging the Gap Between DAOs and the Physical World

### ISSUE THREAD

**Issue by yaoe** [aragon/nest#99]
# Aragon Nest Proposal: Bridging the Gap Between DAOs and the Physical World

## Abstract
The purpose of this project is to find ways for DAOs to be able to interact with non-blockchain based actors, i.e. governments, companies and communities that operates in the physical world, and which are subject to specific jurisdictions. To do so, there are two possible approaches:

* **Creating legal structures for DAOs**: One way is to extend the scope of existing regulatory frameworks to recognize DAOs as legal entity. See e.g., Malta’s proposal of giving legal personhood to DAOs, or to a lesser extent, Delaware’s initiative to allow blockchain-based companies to be registered as standard companies. However, this approach has a series of drawback in that this means reducing a DAO to an existing legal entity, e.g. a company or corporation, which simply mediates its operations through a blockchain, but nonetheless needs to comply with all traditional legal requirements (e.g. director or board of directors, being registered in a particular jurisdictions, etc.)
* **Bridging the gap between DAOs and the physical world**: An alternative way is to maintain the alegality of DAOs but providing some kind of “avatars” for them to interface with the legal world. This means creating a “legal API” between blockchain-based systems and the legal system, that will enable entities from the physical world to interact with these entities according to specific rules. The goal here is not to map DAOs to existing legal concepts, but rather to provide a bridge between the blockchain world and the legal world, without requiring one to subject itself to rules of the other. 

With this project, we want to focus in particular on the second approach, in order to provide new ways for DAOs governed by code to interact with the physical world governed by laws. To do so, we will try to analyse the current regulatory framework in key jurisdictions and devise specific interfaces that will facilitate interactions between these two worlds, with a minimum amount of friction. We will identify the most favorable jurisdictions in which these interfaces can be built, and we will elaborate possible techno-legal frameworks that will constitute the DAOs’ “legal API”. The legal API will account for a variety of ‘functions’:

* **Identity**: How can DAOs be referred to in the physical world, if they are not recognized as a legal entity? Do we need to create a legal avatar or can we refer to them as an object ? 
* **Legal qualification:** How do we avoid DAOs from falling back into the default qualification of a “general partnership”, which might imply legal liability to all of its members? Can we design the DAO in such a way that it automatically acquire another qualification, or do we need to create a specific protocol or legal entity to act as the avatar of the DAO?
* **Property rights**: How do we ensure that the assets owned by the DAO are actually recognized as such, and that they can acquired and transferred legitimately between differents types of actors (DAOs and non-DAOs) ?
* **Contracts:** How can DAOs enter into a contractual transactions with a non-DAO entity, or with another DAO? How can these contractual provisions be enforced? What kind of arbitration or alternative dispute resolution systems do we need to devise for it?

## Scope of Work
We anticipate undertaking and completion of this project will comprise at least one year (September 2018-September 2019) and require the participation and contribution of key experts across a variety of domains and jurisdictions with requisite legal background, technical knowledge, creativity and ability to implement a sound and holistic social and technical vision, within the legal, economic and cultural constraints of the physical world.  We anticipate the entire project will require, for the duration of the year (1) legal research from experts based in relevant legal jurisdictions and (2) technical research to inform the design of the legal API. These research efforts will be intensive in the initial six months as the team maps the topology of blockchain-based systems and how they currently map within existing legal systems. The first six months will require at least two full-time researchers/coordinators, working with a diverse qualified body of external experts, lawyers and researchers on a continuous basis. We also anticipate that such initial research will require team review and feedback in the form of in-person workshops to enable cross-pollination across diverse areas of legal research and  technical design. We anticipate that at least six workshops will be required at a minimum during the year-long project term (approximately once every two months). Based on the results, feedback and iteration of the research and design process during the first six months, the remaining six months of the project will be focused on the formal specification of the legal API, design implementation, and pilot experimentation with our partners.

### Use of funds
* **Research track:** one full-time and one part-time persons working for the duration of the project (one year) to collect all relevant information on an ongoing basis regarding the regulatory frameworks in the selected jurisdictions and cataloguing all relevant legal reforms and statements issued by oversight and regulatory authorities around the world.
* **Development track**: one full-time and one part-time persons working for the duration of the project (one year) to coordinate the work of multiple experts around the various attributes of the ‘legal API’ (identity, legal qualification, property rights, contracts)
* **Workshops**: We will organize a series of research workshops with the COALA community comprising relevant legal, technical and subject-matter experts in order to elaborate the legal API. We plan on organizing six research workshops for the duration of the project (approximately one every two months).
* **Pilots:** Theory is important, but things that work in theory do not always work in practice. We will finds DAOs willing to experiment with our legal API to get real-world feedback on its viability. We will learn from these DAOs’ experience and improve the API on an ongoing manner.

### Subdivision of funds
$54,000 for 1.5 full-time employees ($3,000 / month) for the research track and development track
$36,000 for compensating individual expert contributions who will work with our full-time employees in order to carry on legal research and elaborate the legal API (estimated $3,000 / month)
$36,000 for 6 research workshops ($6,000 / workshop expenses : flight, accommodations, food)
$19,000 as a 15% administration fee for COALA Foundation (coordination and internal costs)

### Grant contract
**Initial Payment:** $25,000
**Recurrent payment:** $20,000 per workshop. Each workshop will be organized around a specific deliverable. At each workshop, we will present the work we have done so far, collect and integrate feedback, and then collaboratively sketch out the work to be done for the next deliverable at the next workshop. 

## Proposed Research Workshops and Deliverables

Kick-off Workshop: October 2018 (Web3 - Berlin)  	- $25,000
-- > **Kick-off meeting**

Workshop #1: November 2018 (IGF - Paris) 		- $20,000
-- > **Topology of legal domains**

Workshop #2: December 2018 (India)			- $20,000
-- > **Legal API - Legal qualification**

Workshop #3: January 2019 (AraCon - Berlin)		- $20,000
-- > **Legal API - Identity**

Workshop #4: March 2019 (Colombia)			- $20,000
-- > **Legal API - Contracts**

Workshop #5: May 2019 (Ann Arbor, MI)		- $20,000
-- > **Legal API - Property Rights**

Final Summit: September 2019 (Boston w/IC3)		- $20,000
-- > **Launch of the Legal API**

## Legal structure
Legal Structure: funds are to be paid to COALA Foundation (a 501(c)(3) non-profit organization incorporated in Delaware, U.S.A. and non-profit organization incorporated in Paris, France).

All work under the COALA Foundation will be released under Creative Commons - BY - SA

## Team
Coordinators:
Primavera De Filippi (20% - 1 day /week)
Constance Choi (20% - 1 day / week)
Hired personnel: 
Full-time position: Greg McMullen
Part-time position: Carla Reyes
Experts:
Fennie Wang, Benedikt Schluppi, Christopher Wray, Anja Blaj, Gian Boescher, Vincent Mignon, Tom, Rick Dudley, Peter Todd, Joseph Poon, Iris Weizmann, Henning Diedrich, Karl Floersch, Vlad Zamfir, Michele Finck, Christoph Jentzsch, Jutta Steiner, Harald Steiber, Brett Scott, Diana Stern, Nate Walker, Ryan Singer, Evan Schwartz, Aaron Wright, Bjorn Wagner, Trent McConaghy, Amor Sexton, Joshua Fairfield, Emin Gun Sirer, Anuj Gupta, Griff (Giveth)

**Comment by mariapao** [comment]
Hi @yaoe We are very excited to see this application! 

The proposal to work on bridging the gap between DAOs and the physical world was already approved so I'm closing this issue and will review the request for funding (the PR).
